### ISSUE TITLE
Need to set cc

### ISSUE THREAD

**Issue by thfuchs** [datawookie/emayili#10]
Hey, thanks for the nice package! Nice to have an option working without java

Could you allow sending mails without the need to set a cc address? Setting `cc` to `NULL` does not send the mail, so only option working for me is specifying `to` and `cc` with the same parameter, which results in two incoming mails

Best regards
Thomas

**Comment by datawookie** [comment]
Hi Thomas,

Thanks for the feedback. Super happy that you are finding `{emayili}` useful. Let's see if we can sort this issue out for you!

This works for me:

```
library(dplyr)
library(emayili)

SMTP_USERNAME = Sys.getenv("SMTP_USER")
SMTP_PASSWORD = Sys.getenv("SMTP_PASSWORD")
SMTP_SERVER = Sys.getenv("SMTP_SERVER")
SMTP_PORT = Sys.getenv("SMTP_PORT")

smtp <- server(host = SMTP_SERVER,
               port = SMTP_PORT,
               username = SMTP_USERNAME,
               password = SMTP_PASSWORD)

email <- envelope() %>%
  from(SMTP_USERNAME) %>%
  to(SMTP_USERNAME) %>%
  subject("subject") %>%
  body("Hello!")

smtp(email, verbose = TRUE)
```

I am only specifying the `To:` address via `to()` without invoking `cc()`.

If you use the `to()`, `cc()` or `bcc()` methods without arguments then they return the respective addresses that are currently attached to the message. So, for example:

```
> email %>% cc()
NULL
> email %>% to()
[1] "andrew@exegetic.biz"
> email %>% cc(NULL)
NULL
> email %>% to(NULL)
[1] "andrew@exegetic.biz"
```

This is why the email is not sent when you set the argument of `cc()` to `NULL`. However, if you are not wanting to specify a `Cc` address then there is no need to use this method at all.

Does this make sense?

Best regards,
Andrew.

**Comment by thfuchs** [comment]
ok yes, my fault, thanks a lot for your patience! Was a problem with the function I wrapped `envelope()` in.
