### ISSUE TITLE
When will a new version be available on CRAN?

### ISSUE THREAD

**Issue by pnacht** [datawookie/emayili#108]
I've been using a relatively old version of `emayili` (0.4.10) and it worked just fine.

However, when I then updated to 0.6.1, the current CRAN version, my code stopped working:

```r
email <- emayili::envelope() %>%
    emayili::from(credentials$username) %>%
    emayili::to(credentials$username) %>%
    emayili::subject("Hi") %>%
    emayili::text("Hoo")

smtp <- emayili::server(
    host = "hi.hoo.com",
    port = 42,
    username = credentials$username,
    password = credentials$password,
    reuse = FALSE
)

smtp(email)
```

The above works perfectly fine in 0.4.10 but hangs in 0.6.1, until it eventually throws an `Error: Request failed after 5 attempts`. I've tried comparing the source code to see what changed and if I had to do something different in this new version, but couldn't figure it out.

However, I then tried updating to the current Github 0.7.0 version and it works just fine once again. (Perhaps prior versions would be sufficient, I only tried with 0.7.0. I did notice that 0.5.6 still worked, so the change happened in 0.6.0).

So, what should I change to get my code working in 0.6.1, or alternatively, when will 0.7.0 be published in CRAN?

**Comment by datawookie** [comment]
Hello Pedro,

...

Best regards, Andrew.

**Comment by pnacht** [comment]
Hey Andrew, I assume that message was supposed to contain some more information?

**Comment by datawookie** [comment]
Hi Pedro, no, not really. It just was a template for the way that I prefer to interact with people. So, getting back to your question, I've just added some new features to the package and am busy ironing out an issue with Spanish encoding on Windows. When that's all sorted I'll put a new version on CRAN. Should be some time next week. Best regards, Andrew.
