### ISSUE TITLE
mime and format

### ISSUE THREAD

**Issue by andrewsrs** [datawookie/emayili#11]
Would it be possible to include a quick example of how these functions are used in the creation of a multi part mime document. I've been playing, but there's no examples, and have had no luck so far.

thanks, andrew

**Comment by datawookie** [comment]
Hi!

Sure. What did you have in mind? What kind of content are you wanting to compose into the message?

/Andrew.

**Comment by datawookie** [comment]
@andrewsrs I didn't get a response from you, so I'm going to close this. Feel free to reopen the issue and give me some specifics on what you have in mind.
