### ISSUE TITLE
[BUG]: Attaching a pdf succesfully sends a mail, but causes RStudio/Shiny Application to freeze for a long time

### ISSUE THREAD

**Issue by CloudStriderGames** [datawookie/emayili#112]
### Description of the bug

Hello, sadly I can't provide much of a log, as RStudio becomes unusable once this happns.

I wanted to send a mail with a PDF attachement. Previously I tested emayili with the given example of mtcars.csv. That worked like a charm.

So I tried another file type for once. A PDF to be precise. After running the Shiny app and clicking the button to send the email I actually received an email with the correct pdf. However the Console kept on printing a mixture of symbols (mostly "A" s and "/"s) 

Kind of like this, but I shortened out a lot of parts (and the initial part was already cut off by the console after the freeze

`...AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
Uploaded 9175040 bytes...AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
...
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAA////////////////////////////////////////////////////////////////
/////////wAAAP//////////////////////////////////////////////////////////////
//////////////////////////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
...
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////////////////////
/////////////////////////////////////////wAAAP//////////////////////////////
////////////////////////////////////////////////////////////////////////////
//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
/////////////////////////////////////////////////////////////////////////wAA
AP//////////////////////////////////////////////////////////////////////////
//////////////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
`

This frozen state lasted more than 15 minutes after I already received the email. I don't think I am doing much wrong, as I just changed the filepath to where the PDF is.

### Steps To Reproduce

use attachment() with a filepath leading to a PDF file. The file was roughly 6.3 MB.

### Additional Information

- Windows 10
- RStudio

EDIT: Just fyi 

host = "smtp.gmail.com"

just in case the host might matter

**Comment by datawookie** [comment]
Hi @CloudStriderGames,

Thanks for this. A little more information would be helpful:

1. What version of `{emayili}` are you using? Did you install from CRAN or GitHub?
2. Please show me the snippet of code from your app where you are sending the message.

Thanks, Andrew.

**Comment by CloudStriderGames** [comment]
Thanks for the quick answer:

0.7.0  (CRAN Version)

```
email <- envelope() %>%
      from("********@gmail.com") %>%
      to("*********@gmail.com") %>%
      subject("This is a plain text message!") %>%
      text("Hello! \n 
           This is a test") %>%
      attachment("C:\\Users\\**********\\Downloads\\Bla.pdf", type = "application/pdf")
    
    smtp <- server(host = "smtp.gmail.com",
                   port = 465,
                   username = "********@gmail.com",
                   password = "********")
    
    smtp(email, verbose = TRUE)
```
Censored some information of course

**Comment by datawookie** [comment]
> Censored some information of course

Naturally. :)

Have you tried replacing `smtp(email, verbose = TRUE)` with `smtp(email)`?

**Comment by CloudStriderGames** [comment]
That accelerated it a lot. Silly of me. But thank you very much for the help!

**Comment by datawookie** [comment]
> That accelerated it a lot.

Well I suspect that any remaining latency is due to communication with the SMTP server and not due to `{emayili}`.

I'm going to remove the bug tag because this really wasn't a bug! :)
