### ISSUE TITLE
[BUG]: Cannot send mails anymore via hotmail

### ISSUE THREAD

**Issue by AdaemmerP** [datawookie/emayili#114]
### Description of the bug

I am running a small shiny app on shinyapps.io, which also sends an email at the end using *emayili*. The app ran perfectly well for months until some days ago. Now, I can neither send an email via the Shiny App anymore nor locally/manually from my Computer.

### Steps To Reproduce

```r
library(emayili)

# Create smtp
   smtp  <- emayili::server(host  = "smtp.live.com",
                            port        = 587,
                            username    = "MyAddress@hotmail.com",
                            password    = "MyPassword")
 
 
 # Test Mail 
   test_mail   <- envelope()                       %>%
                 from("MyAddress@hotmail.com")  %>%
                 to("MyAddress@hotmail.com")    %>%
                 subject("Test Mail")              %>%
                 text("Only a test")

# Send Mail 
 smtp(test_mail, verbose = T)
  

 Trying 204.79.197.212:587...
  Trying 2620:1ec:c11::212:587...
connect to 2620:1ec:c11::212 port 587 failed: Network is unreachable
After 4993ms connect time, move on!
connect to 204.79.197.212 port 587 failed: Connection timed out
Failed to connect to smtp.live.com port 587: Connection timed out
Closing connection 8
Hostname smtp.live.com was found in DNS cache
  Trying 204.79.197.212:587...
  Trying 2620:1ec:c11::212:587...
connect to 2620:1ec:c11::212 port 587 failed: Network is unreachable
After 5000ms connect time, move on!
connect to 204.79.197.212 port 587 failed: Connection timed out
Failed to connect to smtp.live.com port 587: Connection timed out
Closing connection 9
Hostname smtp.live.com was found in DNS cache
  Trying 204.79.197.212:587...
  Trying 2620:1ec:c11::212:587...
connect to 2620:1ec:c11::212 port 587 failed: Network is unreachable
After 5000ms connect time, move on!
connect to 204.79.197.212 port 587 failed: Connection timed out
Failed to connect to smtp.live.com port 587: Connection timed out
Closing connection 10
Hostname smtp.live.com was found in DNS cache
  Trying 204.79.197.212:587...
  Trying 2620:1ec:c11::212:587...
connect to 2620:1ec:c11::212 port 587 failed: Network is unreachable
After 5000ms connect time, move on!
connect to 204.79.197.212 port 587 failed: Connection timed out
Failed to connect to smtp.live.com port 587: Connection timed out
Closing connection 11
Hostname smtp.live.com was found in DNS cache
  Trying 204.79.197.212:587...
  Trying 2620:1ec:c11::212:587...
connect to 2620:1ec:c11::212 port 587 failed: Network is unreachable
After 5000ms connect time, move on!
connect to 204.79.197.212 port 587 failed: Connection timed out
Failed to connect to smtp.live.com port 587: Connection timed out
Closing connection 12
 Error: Request failed after 5 attempts
```

### Additional Information

I am using:
- Debian GNU/Linux 11 (bullseye)
- R version 4.1.2 
- emayili 0.7.0 (CRAN version)

**Comment by datawookie** [comment]
Hi @AdaemmerP, thanks for the bug report. Did you read the log messages though?

I suspect that this is the source of the problem: "Hostname smtp.live.com was found in DNS cache". This is not an `{emayili}` problem, but rather a networking problem (your Shiny app is unable to send messages to that DNS name).

When I try doing that DNS lookup locally I get the IP address that is being attempted.

```
$ nslookup smtp.live.com 
Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
smtp.live.com   canonical name = a-0010.a-msedge.net.
Name:   a-0010.a-msedge.net
Address: 204.79.197.212
Name:   a-0010.a-msedge.net
Address: 2620:1ec:c11::212
```

The fact that the connection is timing out suggests that there is some sort of a networking issue at play.

TBH I am not sure how you would go about sorting this out on shinyapps.io.

Best regards, Andrew.

**Comment by AdaemmerP** [comment]
Dear Andrew,

Thanks for the quick reply! Yes, I saw it and also used 'nslookup', but I was confused because I got the same error message when trying to send an email via gmail using the suggested host name. So basically 'host = smtp.live.com' is outdated and has to be changed in 'emayili::server(...)' to fix the problem?

Again, thanks for your quick response and great package.
Best regards,
Philipp

**Comment by datawookie** [comment]
I guess that there are a few options:

1. There's some sort of networking issue on shinyapps.io.
2. There's a DNS issue (the DNS name is no longer returning the correct IP address).
3. There's a problem with the SMTP server.

> I got the same error message when trying to send an email via gmail using the suggested host name.

I'm not sure that I understand what you mean. Do you mean that you got a similar error when trying to send email via `smtp.gmail.com`?

**Comment by AdaemmerP** [comment]
Thanks! 
Changing the host to 'smtp.office365.com' now allows me to send emails locally. However, the Shiny App is still not working. It seems that it does not recognize the password when using "password  =  Sys.getenv("pwd")" in "emayili::server(...)".
Yat manually typing the password also works for the Shiny App. 

I had an authentication problem with "smtp.gmail.com" but I could solve it now.

**Comment by datawookie** [comment]
@AdaemmerP maybe take a look at this blog post: https://datawookie.dev/blog/2022/01/emayili-sending-email-from-shiny/.

**Comment by AdaemmerP** [comment]
The whole time my shiny app ran like your example with the exception that I only saved my password in '.Renviron'. However, shiny apparently does not find '.Renviron' anymore because Sys.getenv("pwd") is empty.
