### ISSUE TITLE
No known authentication mechanisms supported! in RStudio server 

### ISSUE THREAD

**Issue by mos790** [datawookie/emayili#117]
Hello,

Thanks for this awesome package.

I tried to send some email (Outlook messages) in local with Rstudio, all works well !
But when I switch to Rstudio server (opensource), the same script doesn't work with the following message error `No known authentication mechanisms supported`

Do you know how I can solve this ?

**Code**

```
library(emayili)
email = envelope()
email = envelope(
  from = "xxxxxxx@xxxx.fr",
  to = "xxxxxxx@xxxx.fr",
  subject = "xxxxxxxxxx",
  text = "Hello!!!\nWorld :)"
)
smtp = server(
  host = "xxxxx.xxxxx.org",
  port = 25,
  username = "xxxxxx@xxx.fr",
  password = "xxxxxxx",
  max_times = 1
)
smtp(email, verbose = TRUE)
```

**Error:**

```
No known authentication mechanisms supported!
Closing connection 0
Erreur : Request failed after 1 attempts
Run "rlang::last_error()" to see where the error occurred.
> rlang::last_error()
<error/purrr_error_rate_excess>
Request failed after 1 attempts
Backtrace:
 1. emayili:::smtp(email, verbose = TRUE)
 2. purrr:::send_mail(...)
 3. purrr::rate_sleep(rate, quiet = quiet)
 4. purrr:::stop_rate_excess(rate)
Run "rlang::last_trace()" to see the full context.
```

Thanks

**Comment by datawookie** [comment]
Hi @mostafa790, there is no reason that `{emayili}` should not work from within Shiny. Have you had a look at [this](https://datawookie.dev/blog/2022/01/emayili-sending-email-from-shiny/)? Thanks, Andrew.
