### ISSUE TITLE
[Question]: Not an emayli bug, but why it works with emayli and not with other not completely ! :)

### ISSUE THREAD

**Issue by philibe** [datawookie/emayili#120]
### Description of the bug

Hello.

## The fact with emayli :)

I use your emayli R package to send automatic alert email via smtp, 465 port,  login, password, and everything works fine since months and months.

```
smtp0<- emayili::server(
  host = "smtp.myisp.fr",
  port = 465,
  username = "myuserlogin@myisp.fr",
  password = "xx",
  reuse = FALSE
) 
...

email0 <- emayili::envelope()
email0 <- ( email0 
  %>%   emayili::from(email_from) 
  %>%   emayili::to( email_to ) 
)
```
where email_from is `robots@mysociety.fr`, ie not myisp but it works with our email provider, and email_to is `someone2@mysociety.fr`, or 
`someone3@gmail.com`. And everything works with emayili.

## The fact with other package

I try to send email via Python for an other project but I have on Gmail this warning below with exactly the same parameters at the same time than emayli.

> Process this message with prudence, gmail could not verify that this message comes from

or after many tries nothing and the email is lost..but with emayli it works again after that.

I tried with smtplib and will try with yagmail.

## My question on your SMTP command in emayli

Why Google thinks the email is correct via emayli and not via smtplib. In the log I see that emaily says that server is authentified and in smtplib not. Have I to add `ehlo` or `helo` or other command ?

What SMTP command do you use please ? I have looked in your github source : my knowledge in R permits to read it....but not my knowledge in SMTP.

Regards.

Philippe

### Steps To Reproduce

I am at home, if you accept to read my Python commands, Monday I will paste it at work. But for you it is perhaps out of the scope of this github emayli repository.

**Comment by philibe** [comment]
( I tried to change the label to question or something like that, but I didn't found it)

**Comment by datawookie** [comment]
Hi! Can you send me an email using both processes and I'll take a look at
the headers. You can find my email address in the DESCRIPTION file. Thanks,
Andrew.

**Comment by philibe** [comment]
Thanks. I will do that Monday.

**Comment by philibe** [comment]
Our ISP changed a few weeks ago, and  in fact  the last automatic mail (by emayli), not frequent, was yet warned by gmail..

I changed stmp server but I have problems with ssl and certifcates (Ubuntu 20).

I am studying this :)

**Comment by datawookie** [comment]
Okay, cool. If you want me to delve into this then please send me an email using both processes as mentioned above. I'm going to close this for the moment. If you want to resume, please reopen the issue. Thanks, Andrew.
