### ISSUE TITLE
Authentication going forward

### ISSUE THREAD

**Issue by ajo1993** [datawookie/emayili#121]
Hi, 

I don't know if you've seen this message from Gmail but it seems like Gmail will not support email authentication using third party sites from May 2022 (currently emayili is still working). Emayili seems to have stopped working in the case of Outlook already. It was working fine in January but now just getting the below error:

TCP_NODELAY set
Connection timed out after 10000 milliseconds
Closing connection 20
Hostname smtp.live.com was found in DNS cache

Do you have any tips on whether we'll be able to still send emails from R. I would need to send them from Outlook. In case it is useful this is the code I am using to send from Outlook is:

email_file <- emayili::envelope() %>%
from("xxx") %>%
  to("xxx") %>%
  subject("prova") %>%
  text("prova123")

smtp <- emayili::server(host = "smtp.live.com",
                        port = 587,
                        username = "xxx",
                        password = "xxx")

smtp(email_file, verbose = TRUE)

Thanks a lot. Really hope we find a workaround as emayili is great!

<img width="568" alt="Capture" src="https://user-images.githubusercontent.com/65254910/159160013-4fb1ad07-be52-4873-ad36-609ec87be87a.PNG">

**Comment by datawookie** [comment]
@ajo1993 does [this](https://datawookie.dev/blog/2022/03/updated-gmail-authentication/) help?

**Comment by ajo1993** [comment]
Ah apologies hadn't seen that, yes thanks a lot! 

As for Outlook, do you know if there is some setting that can be changed to make emayili work? There is no "Less secure apps" equivalent there I think. Thanks

Alessandro

**Comment by datawookie** [comment]
@ajo1993 I'm confused by this issue. You seem to be talking about Gmail authentication (and the screenshot definitely pertains to Gmail) but now you are asking about Outlook. These seem to be two distinct issues. Regards, Andrew.
