### ISSUE TITLE
[FEAT]: SendInBlue Support

### ISSUE THREAD

**Issue by Ni-Ar** [datawookie/emayili#123]
### Description

Hi,

I'd be interested in trying your package. Any idea when SendInBlue will be supported as stated at the bottom of [this blog post](https://datawookie.dev/blog/2021/10/emayili-support-for-gmail-sendgrid-mailgun/)?
Thanks!

**Comment by datawookie** [comment]
Already supported. See `sendinblue()` in current CRAN release. Feedback welcome.

**Comment by Ni-Ar** [comment]
oh great, sorry, I didn't read the doc well enough!
