### ISSUE TITLE
[FEAT]: Dependencies

### ISSUE THREAD

**Issue by bkmgit** [datawookie/emayili#126]
### Description

Would be helpful to indicate versions dependencies and versions tested on. On [CRAN](https://cran.r-project.org/web/packages/emayili/index.html) you have :

Imports: | base64enc, commonmark, curl (≥ 4.0), digest, dplyr, glue, htmltools, httr, logger, magrittr, mime, purrr, rmarkdown, rvest, stringi, stringr, tidyr, urltools, xfun, xml2
-- | --
Suggests: | cld2, cld3, gpg, here, jinjar, memoise, testthat (≥ 2.1.0), roxygen2, showtext, Microsoft365R

Imports: 	[base64enc](https://cran.r-project.org/web/packages/base64enc/index.html), [commonmark](https://cran.r-project.org/web/packages/commonmark/index.html), [curl](https://cran.r-project.org/web/packages/curl/index.html) (≥ 4.0), [digest](https://cran.r-project.org/web/packages/digest/index.html), [dplyr](https://cran.r-project.org/web/packages/dplyr/index.html), [glue](https://cran.r-project.org/web/packages/glue/index.html), [htmltools](https://cran.r-project.org/web/packages/htmltools/index.html), [httr](https://cran.r-project.org/web/packages/httr/index.html), [logger](https://cran.r-project.org/web/packages/logger/index.html), [magrittr](https://cran.r-project.org/web/packages/magrittr/index.html), [mime](https://cran.r-project.org/web/packages/mime/index.html), [purrr](https://cran.r-project.org/web/packages/purrr/index.html), [rmarkdown](https://cran.r-project.org/web/packages/rmarkdown/index.html), [rvest](https://cran.r-project.org/web/packages/rvest/index.html), [stringi](https://cran.r-project.org/web/packages/stringi/index.html), [stringr](https://cran.r-project.org/web/packages/stringr/index.html), [tidyr](https://cran.r-project.org/web/packages/tidyr/index.html), [urltools](https://cran.r-project.org/web/packages/urltools/index.html), [xfun](https://cran.r-project.org/web/packages/xfun/index.html), [xml2](https://cran.r-project.org/web/packages/xml2/index.html)
Suggests: 	[cld2](https://cran.r-project.org/web/packages/cld2/index.html), [cld3](https://cran.r-project.org/web/packages/cld3/index.html), [gpg](https://cran.r-project.org/web/packages/gpg/index.html), [here](https://cran.r-project.org/web/packages/here/index.html), [jinjar](https://cran.r-project.org/web/packages/jinjar/index.html), [memoise](https://cran.r-project.org/web/packages/memoise/index.html), [testthat](https://cran.r-project.org/web/packages/testthat/index.html) (≥ 2.1.0), [roxygen2](https://cran.r-project.org/web/packages/roxygen2/index.html), [showtext](https://cran.r-project.org/web/packages/showtext/index.html), [Microsoft365R](https://cran.r-project.org/web/packages/Microsoft365R/index.html)

In particular magritrr seems to need a fairly recent version

**Comment by datawookie** [comment]
@bkmgit I think that this is a brilliant idea. I'm very much in favour of explicit versioning of dependencies. Would you like to kick off the process (perhaps starting with `{magrittr}`) and then submit a PR? Thanks, Andrew.

**Comment by bkmgit** [comment]
Ok, https://r-pkgs.org/description.html#minimum-versions suggests to do this with care.  With magrittr version 1.5 one gets the error message `Error : 'pipe_nested' is not an exported object from 'namespace:magrittr'` when trying to install emayili 0.7.5, with 2.0.1 this error does not occur.
