### ISSUE TITLE
[FEAT]: store SMTP setting in local file

### ISSUE THREAD

**Issue by selesnow** [datawookie/emayili#132]
### Description

Hi, 

in README examples i was find:

```r
smtp <- server(
  host = "smtp.gmail.com",
  port = 465,
  username = "bob@gmail.com",
  password = "bd40ef6d4a9413de9c1318a65cbae5d7"
)
smtp(email, verbose = TRUE)
```

But add and stored password in code is bad practice. Could you show example how stored SMTP settings in local file?

You can add a mechanism to store and read SMTP settings from a local file, if it exists.

**Comment by datawookie** [comment]
Thanks for the suggestion, @selesnow. Fixed in 4eb3009cea9e24f9f8bfa1a49382ff1becdd0b81.
