### ISSUE TITLE
Different mail rendering Outlook vs Gmail

### ISSUE THREAD

**Issue by ScaonE** [datawookie/emayili#135]
Dear all,

After asking Andrew about "duplicates policy", I allow myself to [link a related issue](https://github.com/rstudio/blastula/issues/289) I posted on another repository.

Best regards

**Comment by datawookie** [comment]
Hi @ScaonE, please see [my comment](https://github.com/rstudio/blastula/issues/289#issuecomment-1160507011) on your other issue. Best regards, Andrew.
