### ISSUE TITLE
[BUG]: Umlauts in rmarkdown render are not displayed

### ISSUE THREAD

**Issue by pasipasi123** [datawookie/emayili#137]
### Description of the bug

When rendering a Rmd file, umlauts are not displayed. 

It is possible to render umlaut characters by rendering a character string with umlauts. `rmarkdown::render()` renders umlauts just fine. I can also display umlauts in the message by using `html()`.

### Steps To Reproduce

```
library(emayili)
library(stringr)

writeLines('---
  output: html_document
---
## headline 
öäå need to see those umlauts
', "test.Rmd")

email1 <- envelope() %>% 
  render("test.Rmd")

email2 <- envelope() %>% 
  render("öäå need to see those umlauts")

email1$parts[[1]][["content"]] %>% 
  str_sub(-113, -1)
#> [1] "<h2>headline</h2>\r\n<p><f6><e4><e5> need to see those umlauts</e5></e4></f6></p>\r\n</div>\r\n</div>\r\n</body>\r\n</html>"
  
email2$parts[[1]][["content"]]
#> [1] "<html><body><p>öäå need to see those umlauts</p></body></html>"
```
In `email1` `ä` turns in to `<e4></e4>` tag and so on.

### Additional Information

```
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=Finnish_Finland.1252  LC_CTYPE=Finnish_Finland.1252    LC_MONETARY=Finnish_Finland.1252
[4] LC_NUMERIC=C                     LC_TIME=Finnish_Finland.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] stringr_1.4.0  emayili_0.7.10

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.9       pillar_1.8.0     compiler_4.1.0   base64enc_0.1-3  tools_4.1.0      digest_0.6.29    evaluate_0.15   
 [8] lifecycle_1.0.1  tibble_3.1.8     pkgconfig_2.0.3  rlang_1.0.4      DBI_1.1.3        cli_3.3.0        rstudioapi_0.13 
[15] commonmark_1.8.0 curl_4.3.2       xfun_0.31        fastmap_1.1.0    dplyr_1.0.9      httr_1.4.3       xml2_1.3.3      
[22] knitr_1.39       generics_0.1.3   vctrs_0.4.1      triebeard_0.3.0  tidyselect_1.1.2 glue_1.6.2       R6_2.5.1        
[29] fansi_1.0.3      rmarkdown_2.14   purrr_0.3.4      tidyr_1.2.0      logger_0.2.2     magrittr_2.0.3   urltools_1.7.3  
[36] htmltools_0.5.3  assertthat_0.2.1 rvest_1.0.2      mime_0.12        utf8_1.2.2       stringi_1.7.8   
```

**Comment by datawookie** [comment]
Hi @pasipasi123,

I am not able to reproduce your issue. This is the code that I am running:

```
library(emayili)
library(magrittr)

writeLines('---
output: html_document
---
## headline 
öäå need to see those umlauts
', "test.Rmd")

smtp <- server(
  host = Sys.getenv("SMTP_SERVER"),
  port = Sys.getenv("SMTP_PORT"),
  username = Sys.getenv("SMTP_USERNAME"),
  password = Sys.getenv("SMTP_PASSWORD")
)

envelope(
  to = Sys.getenv("SMTP_USERNAME"),
  from = Sys.getenv("SMTP_USERNAME"),
  subject = "Umlaut in Rmd"
) %>%
  render("test.Rmd") %>%
  smtp()

envelope(
  to = Sys.getenv("SMTP_USERNAME"),
  from = Sys.getenv("SMTP_USERNAME"),
  subject = "Umlaut in Markdown"
) %>% 
  render("öäå need to see those umlauts") %>%
  smtp()
```

Below are screenshots from my email client showing the received emails.

![image](https://user-images.githubusercontent.com/6134409/182418603-7ab6f962-a893-4e4a-a6c4-c5283bd19eb8.png)
![image](https://user-images.githubusercontent.com/6134409/182418650-74c3e8f7-f440-4102-b963-135a915810e0.png)

In both cases the umlaut is present in the email message.

What version of `{emayili}` are you using? Perhaps try installing the latest version from GitHub?

Also, in the interests of debugging, please can you send me an email using your code (you can use the email address listed for the package). I'll then dig into the details and see if I can discern the problem that you are experiencing.

My immediate assumption is that the issue you are experiencing is either related to (i) the platform that you are running R on, although I know of a number of people who are successfully using `{emayili}` on Windows or (ii) your locale, which I see is set to Finnish_Finland.1252.

Best regards, Andrew.

**Comment by pasipasi123** [comment]
Thanks for looking into this. 

I can reproduce my issue on another Windows machine, but not on a Linux machine. I've tried the latest CRAN version of `emayili` and the GitHub version with the same results. 

I've also tried to change the locale to English, but that does not help. I removed the header from the Rmd to ease reprex creation and added the `rmarkdown` render bit to show that the Rmd file is actually fine:

```
library(emayili)
library(stringr)

options(encoding = "UTF-8")
Sys.setlocale("LC_ALL", "English")
#> [1] "LC_COLLATE=English_United States.1252;LC_CTYPE=English_United States.1252;LC_MONETARY=English_United States.1252;LC_NUMERIC=C;LC_TIME=English_United States.1252"

writeLines('## headline 
öäå need to see those umlauts
', "test.Rmd")

email1 <- envelope() %>% 
  render("test.Rmd")

email1$parts[[1]][["content"]] %>% 
  str_sub(-113, -1)
#> [1] "<h2>headline</h2>\r\n<p><f6><e4><e5> need to see those umlauts</e5></e4></f6></p>\r\n</div>\r\n</div>\r\n</body>\r\n</html>"

rmarkdown::render("test.Rmd")
#> processing file: test.Rmd
#> output file: test.knit.md
# .... [removed]
#> 
#> Output created: test.html

library(rvest)

html <- read_html("test.html")
html %>% 
  html_nodes(xpath = '//*[@id="headline"]')
#> {xml_nodeset (1)}
#> [1] <div id="headline" class="section level2">\r\n<h2>headline</h2>\r\n<p>öäå ...
```
I sent you an umlaut email.

**Comment by datawookie** [comment]
Hi @pasipasi123,

Thanks for that. Unfortunately the email you sent wasn't very helpful. It basically just replicated what you show above. Not surprising, but it's good to have this confirmed.

This is tricky to debug because I can't reproduce the problem locally. However, what I hope to do it narrow down _where_ the problem is occurring in the code. To this end I have created a separate experimental branch on GitHub. Would you mind please installing from that branch as follows:

```
remotes::install_github("datawookie/emayili@umlaut")
```

Once that install completes, please restart R (to ensure that you load the most recent `{emayili}`) and run the following code:

```
library(emayili)
library(logger)

log_threshold(DEBUG)

envelope() %>% 
  render("öäå need to see those umlauts") %>%
  print(details = TRUE)
```

Can you please copy the output into your response? Appreciate your help debugging this problem.

Thank you, Andrew.

**Comment by datawookie** [comment]
Incidentally, I have made some progress on understanding this:

```
<p><f6><e4><e5> need to see those umlauts</e5></e4></f6></p>
```

Those mystery tags (`<f6>`, `<e4>` and `<e5>`) are actually the hex codes for those characters. Now I just need to figure out what's turning them into HTML tags.

![image](https://user-images.githubusercontent.com/6134409/182659884-725d92d1-84d1-4d18-8e0f-0587bd0405bd.png)

**Comment by pasipasi123** [comment]
I installed the umlaut branch and got this. I also ran the Rmd render with logger but it errors out on some formatting and advices `Please consider using another ``log_formatter`` or ``skip_formatter`` on strings with curly braces.` 
```
> envelope() %>% 
+   render("öäå need to see those umlauts") %>%
+   print(details = TRUE)
DEBUG   [2022-08-04 08:43:35.345] Interpreting input as character vector.
DEBUG   [2022-08-04 08:43:35.348] Assuming input is Plain Markdown.
DEBUG   [2022-08-04 08:43:35.353] text: öäå need to see those umlauts
DEBUG   [2022-08-04 08:43:35.358] rendered markdown: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><p>öäå need to see those umlauts</p></body></html>
DEBUG   [2022-08-04 08:43:35.362] - Retain CSS from inline <link> tags.
DEBUG   [2022-08-04 08:43:35.366] - Remove CSS from external <link> tags.
DEBUG   [2022-08-04 08:43:35.370] - Retain inline <style>.
DEBUG   [2022-08-04 08:43:35.374] after styles: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><p>öäå need to see those umlauts</p></body></html>
DEBUG   [2022-08-04 08:43:35.379] No embedded <style>.
DEBUG   [2022-08-04 08:43:35.383] - Remove various tags.
DEBUG   [2022-08-04 08:43:35.386] HTML: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><p>öäå need to see those umlauts</p></body></html>
DEBUG   [2022-08-04 08:43:35.389] - Remove comments.
DEBUG   [2022-08-04 08:43:35.392] HTML: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><p>öäå need to see those umlauts</p></body></html>
DEBUG   [2022-08-04 08:43:35.395] Adding first child.
DEBUG   [2022-08-04 08:43:35.398] Content-Type:                 text/html; 
                              charset=utf-8

<html><body><p>öäå need to see those umlauts</p></body></html>
Date:                         Thu, 04 Aug 2022 05:43:35 GMT
X-Mailer:                     {emayili}-0.7.10
MIME-Version:                 1.0
Content-Type:                 text/html; 
                              charset=utf-8

<html><body><p>öäå need to see those umlauts</p></body></html>
```

Rendering the Rmd errors out quite early but we can see that the umlauts are already gone at the beginning. 

```
> envelope() %>% 
+   render("test.Rmd")  
DEBUG   [2022-08-04 08:45:37.544] Interpreting input as path to file.
DEBUG   [2022-08-04 08:45:37.547] Assuming input is R Markdown.
DEBUG   [2022-08-04 08:45:37.573] text: ## headline 
��� need to see those umlauts
```

**Comment by datawookie** [comment]
Aha! Okay, the `.Rmd` approach is not going to work on this branch. Let's just focus on getting it working from a Markdown string. Can you please test sending from this branch.

Please take this basic message

```
envelope() %>% 
+   render("öäå need to see those umlauts")
```

and add a subject, then send it to me via `{emayili}`.

**Comment by pasipasi123** [comment]
Sending a markdown string with umlauts works fine. Do you still want it sent? Sorry if I wasn't clear in the beginning.

**Comment by datawookie** [comment]
Hmmm. Yes, indeed, there was some misunderstanding there. Anyway, I understand what the problem is now. :)

I've pushed some more debugging code to that branch. Can you please install from GitHub again (using the same command as before, where the `umlaut` branch is specified).

Then please run the following code and add the results to this issue. Sorry, the output is messy, but it should hopefully tell me what I need to know.

```
library(emayili)
library(logger)

log_threshold(DEBUG)

writeLines('---
output: html_document
---
## headline 
öäå need to see those umlauts
', "test.Rmd")

envelope() %>% 
  render("test.Rmd")
```

**Comment by pasipasi123** [comment]
I'm getting this. 

```
> envelope() %>% 
+   render("test.Rmd")
DEBUG   [2022-08-05 10:15:35.068] Interpreting input as path to file.
DEBUG   [2022-08-05 10:15:35.074] text from file: ---
output: html_document
---
## headline 
��� need to see those umlauts
[1] "---\noutput: html_document\n---\n## headline \n\xf6\xe4\xe5 need to see those umlauts\n"
DEBUG   [2022-08-05 10:15:35.078] Assuming input is R Markdown.
NULL
DEBUG   [2022-08-05 10:15:35.104] text from file: 
[1] ""
DEBUG   [2022-08-05 10:15:35.110] text: ---
output: html_document
---
## headline 
��� need to see those umlauts
DEBUG   [2022-08-05 10:15:37.912] - Retain CSS from inline <link> tags.
DEBUG   [2022-08-05 10:15:37.916] - Remove CSS from external <link> tags.
DEBUG   [2022-08-05 10:15:37.920] - Retain inline <style>.
{xml_nodeset (1)}
[1] <div id="headline" class="section level2">\r\n<h2>headline</h2>\r\n<p><f6><e4><e5> need to see those umlauts</e5></e ...
DEBUG   [2022-08-05 10:15:37.935] text from file: 
[1] ""
DEBUG   [2022-08-05 10:15:37.967] text from file: 
[1] ""
DEBUG   [2022-08-05 10:15:37.969] - Remove various tags.
DEBUG   [2022-08-05 10:15:37.972] HTML: <!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>file11f8c3a9605.knit</title>
<!-- tabsets --><!-- code folding -->
</head>
<body>


<div class="container-fluid main-container">




<div id="header">




</div>


<div id="headline" class="section level2">
<h2>headline</h2>
<p><f6><e4><e5> need to see those umlauts</e5></e4></f6></p>
</div>




</div>

<!-- tabsets --><!-- code folding --><!-- dynamically load mathjax for compatibility with self-contained -->
</body>
</html>
DEBUG   [2022-08-05 10:15:37.974] - Remove comments.
DEBUG   [2022-08-05 10:15:37.977] HTML: <!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>file11f8c3a9605.knit</title>
</head>
<body>


<div class="container-fluid main-container">




<div id="header">




</div>


<div id="headline" class="section level2">
<h2>headline</h2>
<p><f6><e4><e5> need to see those umlauts</e5></e4></f6></p>
</div>




</div>

</body>
</html>
DEBUG   [2022-08-05 10:15:37.979] - Consolidate CSS.
Warning message:
package ‘rvest’ was built under R version 4.1.3 
```

**Comment by datawookie** [comment]
Okay, we're getting somewhere now. :) I'll work on this later today. May need you to try some more things for me. Thanks for your patience. This is really not the ideal way to do debugging. But it's a good lesson in collaboration.

**Comment by pasipasi123** [comment]
I'm happy to help. Many thanks for your patience! Great package btw, it's a pleasure to use.

**Comment by datawookie** [comment]
I think that this has something to do with the way that the `.Rmd` is being read from disk. Can you please send me the output from the following?

```
library(stringi)

writeLines("#Header\nöäå need to see those umlauts", "test.Rmd")

text <- readLines("test.Rmd", encoding = "UTF-8", warn = FALSE)

print(text)

text <- stri_read_lines("test.Rmd")

print(text)

text <- stri_read_lines("test.Rmd", encoding = "UTF-8")

print(text)
```

**Comment by datawookie** [comment]
@pasipasi123 could you please send me the output from :point_up:? Thanks!

**Comment by pasipasi123** [comment]
Sorry, it took some time to get back into this. During the weekend I tried this with a third computer, my personal Windows 10 machine, and could not reproduce the original issue and therefore saw no reason to run any reprexes.  

My default text encoding in Rstudio is UTF-8. Looks like I'm not writing UTF-8 though.

Here are 3 code chunks: 

1) reprex of your code
2) same as above but with `options(encoding = "UTF-8")`
3) copypaste of 2)'s console output

``` r
library(stringi)

writeLines("#Header\nöäå need to see those umlauts", "test.Rmd")

text <- readLines("test.Rmd", encoding = "UTF-8", warn = FALSE)

print(text)
#> [1] "#Header"                               
#> [2] "<f6><e4><e5> need to see those umlauts"

text <- stri_read_lines("test.Rmd")

print(text)
#> [1] "#Header"                       "öäå need to see those umlauts"

text <- stri_read_lines("test.Rmd", encoding = "UTF-8")
#> Warning in stri_encode(txt, encoding, "UTF-8"): input data \xfffffff6 in the
#> current source encoding could not be converted to Unicode
#> Warning in stri_encode(txt, encoding, "UTF-8"): input data \xffffffe4 in the
#> current source encoding could not be converted to Unicode
#> Warning in stri_encode(txt, encoding, "UTF-8"): input data \xffffffe5 in the
#> current source encoding could not be converted to Unicode

print(text)
#> [1] "#Header"                       "<U+FFFD><U+FFFD><U+FFFD> need to see those umlauts"
```

<sup>Created on 2022-08-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

If I add an encoding option:


``` r
library(stringi)

options(encoding = "UTF-8")

writeLines("#Header\n<f6><e4><e5> need to see those umlauts", "test.Rmd")

text <- readLines("test.Rmd", encoding = "UTF-8", warn = FALSE)

print(text)
#> [1] "#Header"                               
#> [2] "<f6><e4><e5> need to see those umlauts"

text <- stri_read_lines("test.Rmd")

print(text)
#> [1] "#Header"                          "öäå need to see those umlauts"

text <- stri_read_lines("test.Rmd", encoding = "UTF-8")

print(text)
#> [1] "#Header"                       "<f6><e4><e5> need to see those umlauts"
```

<sup>Created on 2022-08-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

However the code output in console (fresh session) with the encoding option set looks different than in the reprex.

```
> text <- readLines("test.Rmd", encoding = "UTF-8", warn = FALSE)
> print(text)
[1] "#Header"                                "\xf6\xe4\xe5 need to see those umlauts"
> text <- stri_read_lines("test.Rmd")
> print(text)
[1] "#Header"                          "Ã¶Ã¤Ã¥ need to see those umlauts"
> text <- stri_read_lines("test.Rmd", encoding = "UTF-8")
> print(text)
[1] "#Header"                       "öäå need to see those umlauts"
```

**Comment by datawookie** [comment]
Aha! Okay, so it looks like using `stri_read_lines()` with no encoding option should do the trick.

I have updated that test branch in the repository. Would you mind please running `remotes::install_github("datawookie/emayili@umlaut")` and then testing again? Thank you!

**Comment by datawookie** [comment]
@pasipasi123 could you please try :point_up:? Thanks!

**Comment by pasipasi123** [comment]
I get encoding warnings but the umlaut characters seem to be there.

``` r
library(emayili)
library(stringr)

writeLines('## headline 
öäå need to see those umlauts
', "test.Rmd")

email <- envelope() %>% 
  render("test.Rmd")
#> Warning in readLines(con, warn = FALSE): invalid input found on input connection
#> 'file18b805401fd0.Rmd'
#> Warning in xfun::read_utf8(input): The file file18b805401fd0.Rmd is not encoded
#> in UTF-8. These lines contain invalid UTF-8 characters: 2
#> Warning in readLines(con, warn = FALSE): invalid input found on input connection
#> 'file18b805401fd0.knit.md'

#> Warning in readLines(con, warn = FALSE): invalid input found on input connection
#> 'file18b805401fd0.knit.md'

email$parts[[1]][["content"]] %>% 
  str_sub(-113, -1)
#> [1] "lass=\"section level2\">\r\n<h2>headline</h2>\r\n<p>öäå need to see those umlauts</p>\r\n</div>\r\n</div>\r\n</body>\r\n</html>"
```

<sup>Created on 2022-08-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by datawookie** [comment]
Aha! Thank you. Okay, I feel we are millimetres away from a fix. I'm astonished that we are getting warnings from `readLines` despite setting `warn = FALSE`!

**Comment by datawookie** [comment]
@pasipasi123 I have cleaned things up and pushed a fix to the `fix-umlaut` branch. Would you mind testing please?

Install with `remotes::install_github("datawookie/emayili@fix-umlaut")`.

Thanks for your persistence with this! :+1:

**Comment by pasipasi123** [comment]
Still getting warnings.

``` r
remotes::install_github("datawookie/emayili@fix-umlaut")
#> Skipping install of 'emayili' from a github remote, the SHA1 (b924038b) has not changed since last install.
#>   Use `force = TRUE` to force installation

library(emayili)
library(stringr)

writeLines('## headline 
öäå need to see those umlauts
', "test.Rmd")

email <- envelope() %>% 
  render("test.Rmd")
#> Warning in readLines(con, warn = FALSE): invalid input found on input connection
#> 'file106c850de1a2f.Rmd'
#> Warning in xfun::read_utf8(input): The file file106c850de1a2f.Rmd is not encoded
#> in UTF-8. These lines contain invalid UTF-8 characters: 2
#> Warning in readLines(con, warn = FALSE): invalid input found on input connection
#> 'file106c850de1a2f.knit.md'

#> Warning in readLines(con, warn = FALSE): invalid input found on input connection
#> 'file106c850de1a2f.knit.md'

email$parts[[1]][["content"]] %>% 
  str_sub(-113, -1)
#> [1] "lass=\"section level2\">\r\n<h2>headline</h2>\r\n<p>öäå need to see those umlauts</p>\r\n</div>\r\n</div>\r\n</body>\r\n</html>"
```

<sup>Created on 2022-08-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by datawookie** [comment]
@pasipasi123 please can you set `options(warn = 2)` and run that again? Need to know where those warnings are being generated.

**Comment by pasipasi123** [comment]
``` r
options(warn = 2)

library(emayili)
library(stringr)

writeLines('## headline 
öäå need to see those umlauts
', "test.Rmd")

email <- envelope() %>% 
  render("test.Rmd")
#> Error in readLines(con, warn = FALSE): (converted from warning) invalid input found on input connection 'file34f871166c5.Rmd'

email$parts[[1]][["content"]] %>% 
  str_sub(-113, -1)
#> Error in stri_sub(string, from = start, to = end): object 'email' not found
```

<sup>Created on 2022-08-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by datawookie** [comment]
Hmmm. This is very weird. You are still getting a warning on files which are being pulled from an URL.

Okay, I have replaced all occurrences of `readLines()` with `stri_read_lines()`. This was what fixed the original problem.

@pasipasi123 please test again. Hopefully for the very last time! :pray:

**Comment by pasipasi123** [comment]
I'm still seeing `readLines()` warnings even though I have the latest `fix-umlaut` branch installed.

``` r
remotes::install_github("datawookie/emayili@fix-umlaut")
#> Skipping install of 'emayili' from a github remote, the SHA1 (9cebd9d1) has not changed since last install.
#>   Use `force = TRUE` to force installation

library(emayili)
library(stringr)

writeLines('## headline 
öäå need to see those umlauts
', "test.Rmd")

email <- envelope() %>% 
  render("test.Rmd")
#> Warning in readLines(con, warn = FALSE): invalid input found on input connection
#> 'file50c84fe64d6.Rmd'
#> Warning in xfun::read_utf8(input): The file file50c84fe64d6.Rmd is not encoded
#> in UTF-8. These lines contain invalid UTF-8 characters: 2
#> Warning in readLines(con, warn = FALSE): invalid input found on input connection
#> 'file50c84fe64d6.knit.md'

#> Warning in readLines(con, warn = FALSE): invalid input found on input connection
#> 'file50c84fe64d6.knit.md'

email$parts[[1]][["content"]] %>% 
  str_sub(-113, -1)
#> [1] "lass=\"section level2\">\r\n<h2>headline</h2>\r\n<p>öäå need to see those umlauts</p>\r\n</div>\r\n</div>\r\n</body>\r\n</html>"
```

<sup>Created on 2022-08-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by datawookie** [comment]
Aha! Okay, @pasipasi123, well there are no longer any calls to `readLines()` in the `{emayili}` code. So this means that the warning is being generated in another library which is being called from one of the `{emayili}` functions.

Are you still up for further debugging? Can you please:

1. Set `options(warn = 2)`.
2. Run your script one line at a time until there's a warning (which will be translated into an error because of the previous command).
3. Run `traceback()`, which will dump the backtrace from the error, which will enable us to see where the error (or warning, actually!) is being generated.

**Comment by pasipasi123** [comment]
Here's my output. Sorry again for the delay. 

```
> remotes::install_github("datawookie/emayili@fix-umlaut")
Skipping install of 'emayili' from a github remote, the SHA1 (9cebd9d1) has not changed since last install.
  Use `force = TRUE` to force installation
> 
> options(warn = 2)
> library(emayili)

Attaching package: ‘emayili’

The following object is masked from ‘package:graphics’:

    text

The following object is masked from ‘package:methods’:

    signature

The following objects are masked from ‘package:base’:

    local, raw

> library(stringr)
> writeLines('## headline 
+ öäå need to see those umlauts
+ ', "test.Rmd")
> email <- envelope() %>% 
+   render("test.Rmd")
 Error in readLines(con, warn = FALSE) : 
(converted from warning) invalid input found on input connection 'file18b7875676600.Rmd' 
> traceback()
14: doWithOneRestart(return(expr), restart)
13: withOneRestart(expr, restarts[[1L]])
12: withRestarts({
        .Internal(.signalCondition(simpleWarning(msg, call), msg, 
            call))
        .Internal(.dfltWarn(msg, call))
    }, muffleWarning = function() NULL)
11: .signalSimpleWarning("invalid input found on input connection 'file18b7875676600.Rmd'", 
        base::quote(readLines(con, warn = FALSE)))
10: readLines(con, warn = FALSE)
9: read_utf8(knit_input)
8: rmarkdown::render(input, output_format = output_format, output_file = output, 
       params = params, quiet = TRUE, envir = new.env()) at render.R#59
7: (function (msg, markdown, params = NULL, squish = TRUE, css, 
       include_css, language) 
   {
       stopifnot(is.null(params) || is.list(params))
       if (plain <- attr(markdown, "plain")) {
           output <- markdown_html(markdown) %>% read_html()
       }
       else {
           input <- tempfile(fileext = ".Rmd", tmpdir = getwd())
           output <- sub("\\.Rmd", ".html", input)
           on.exit(unlink(sub("\\.Rmd", "*", input), recursive = TRUE))
           cat(markdown, file = input)
           output_format <- html_document(self_contained = TRUE, 
               pandoc_args = "--quiet")
           output_format$knitr$knit_hooks <- list(plot = function(x, 
               options) {
               caption <- options$fig.cap
               alt <- options$fig.alt
               if (is.null(alt)) alt <- caption
               class <- options$fig.class
    ...
6: eval(mc, parent.frame())
5: eval(mc, parent.frame())
4: withVisible(eval(mc, parent.frame()))
3: manifest(msg, markdown, params, squish, css = list(extra = read_text(css_files)), 
       include_css, language) at render.R#267
2: render(., "test.Rmd")
1: envelope() %>% render("test.Rmd")
```

**Comment by datawookie** [comment]
Aha! Okay, that warning is being generated by a call to `read_utf8()` from within `rmarkdown::render()`. This is a locally declared version of `read_utf8()` (not the one from the `{xfun}` package), which in turn calls `readLines()`.

That is the origin of the first warning:

```
#> Warning in readLines(con, warn = FALSE): invalid input found on input connection
#> 'file50c84fe64d6.Rmd'
```

The other warnings all relate to the same issue.

The second warning actually tells us where the problem is (line 2 of the input file):

```
#> Warning in xfun::read_utf8(input): The file file50c84fe64d6.Rmd is not encoded
#> in UTF-8. These lines contain invalid UTF-8 characters: 2
```

This is what the input file looks like:

```
## headline 
öäå need to see those umlauts
```

So clearly it is objecting to the accented characters at the beginning of that line.

**Comment by datawookie** [comment]
@pasipasi123 I _think_ that the issue is that I'm creating a file (the temporary file mentioned in the warning messages) using the `cat()` function and I _suspect_ that this is not setting the encoding of the file appropriately.

I have replaced the call to `cat()` with `stri_write_lines()` in the hope that it will "do the right thing".

Could I impose on you to install the latest version from the `fix-umlaut` branch and test again please? :pray: Thank you!

**Comment by pasipasi123** [comment]
I now have some extra files. No warnings or errors. The rendered html does have the umlauts.

```
> email <- envelope() %>% 
+   render("test.Rmd")
[1] "Input file: C:/Users/[----]\\file13614272c75c9.Rmd <f0><9f><9a><a8> Don't delete me!"
```

**Comment by datawookie** [comment]
Hi @pasipasi123, okay, I have cleaned things up and merged those changes back into the `master` branch. Can you please confirm that this ticks all boxes for you? Ideally please install from the `master` branch and test. If you are happy with the results then I will push an update to CRAN. Thanks, Andrew.

**Comment by pasipasi123** [comment]
Looks great, I'm seeing those umlauts in a markdown email now. 

As a side note, I'm wondering why I'm getting this in the beginning of the email? `Date: Wed, 17 Aug 2022 05:34:11 GMT X-Mailer: {emayili}-0.7.10 MIME-Version: 1.0 Content-Type: text/html; charset=utf-8` I haven't seen it before, but I have not send any Rmd emails lately.

**Comment by datawookie** [comment]
> Looks great, I'm seeing those umlauts in a markdown email now.

Awesome! :)

**Comment by datawookie** [comment]
> I'm wondering why I'm getting this in the beginning of the email?

@pasipasi123 that's weird. I'm not getting that in rendered emails. Those are header records which should be at the top of any email message. But they should not show up in your email client. Could you please provide me with more information? Maybe send such an email to me so that I can see the problem? Please use email address from the `DESCRIPTION` file. Thanks.

Please also show me the code you're using to generate the email with this problem. Thanks!

**Comment by pasipasi123** [comment]
Nevermind actually, my bad, sorry! I sent emails too quickly without looking closely what's going to be sent. 

Basically what happened was that I sent `html(envelope %>% render("test.Rmd"))` instead of just `render("test.Rmd")` because I was lazily using a function where I had previously switched to rendering html instead of a Rmd file.

**Comment by datawookie** [comment]
Whew! Thanks so much for working with me on this over the last weeks. I think that this has resulted in a general improvement of the code. I'll push out a new release today.
