### ISSUE TITLE
Development version of curl not required

### ISSUE THREAD

**Issue by KZARCA** [datawookie/emayili#14]
Hi,
it seems that the version of curl available on cran (4.2) is sufficient. No need to install the development version anymore.
Best

**Comment by datawookie** [comment]
Hi!

Yes, you're right. It was updated to include the required features.

I'll sort out the README.

Thanks for the heads-up.

Best regards,
Andrew.

**Comment by datawookie** [comment]
Also, please let me know if you encounter any issues with `{emayili}`. Definitely still a work in progress.

**Comment by KZARCA** [comment]
Of course! 
BTW this package is great as having very few dependencies. Are you planning to push it on CRAN?

**Comment by datawookie** [comment]
Thanks!

Yes, I am planning on putting it on CRAN. Was actually just waiting to get some user feedback. I suppose I'm more or less there. If you can confirm that it's working well for you then I guess that's probably enough confirmation for me and I'll start the arduous CRAN submission process. :)
