### ISSUE TITLE
[FEAT]: Expose `use_ssl` as an input argument in `server` function

### ISSUE THREAD

**Issue by lukashaenjes** [datawookie/emayili#151]
### Description

Hi there, thanks for this nice and lean package!

I used it to successfully connect to an SMTP server requiring authentication. However, the server has a somewhat unusual setup in that it listens (only) on port 25 but still requires a STARTTLS command to successfully send out e-mails.

I had a hard time implementing this because the `use_ssl` argument, which is later forwarded to `curl::send_mail()`, is only set within the `server` function itself based on the port:

https://github.com/datawookie/emayili/blob/5501248aa422c044900b5ab1f45484b3a4faa23d/R/server.R#L98-L102

I ended up monkey-patching the `server` function before calling it to hard-set `use_ssl` to 1 regardless of the specified `port`:

```R
# MONKEYPATCH: access `server` function and hard-set `use_ssl` to 1 regardless
# of specified port
body(server)[[4]] <- substitute(use_ssl <- 1)
```

This works, but it's admittedly a bit clunky. While unusual (I guess), one can use the STARTTLS command while still using port 25, which is also reflected in the `curl::send_mail` [documentation](https://rdrr.io/cran/curl/man/send_mail.html):

> If your email server listens on port 25 or 587, use an `smtp://` URL in combination with the `use_ssl` parameter to control if the connection should be upgraded with STARTTLS. 

My feature request would therefore be to simply expose `use_ssl` as an input argument in the `server` function so it can be freely set by the user. We could even continue setting the default value based on the port but making it easy to override this way.

Happy to open a PR if you agree this would be a useful feature!

**Comment by datawookie** [comment]
Hi @lukasfeick-sw, this is a great suggestion. I have implemented on the `use-ssl` branch. Would you mind please testing that it satisfies your requirements? Thanks, Andrew.

**Comment by lukashaenjes** [comment]
Hi @datawookie, many thanks for the quick implementation and apologies for the late reply. I now had the chance to check your implementation.

One thing I noticed is that it currently crashes because of a wrong argument:

https://github.com/datawookie/emayili/blob/df160f3a504d76cc90ecc196ea0ea0d90b834e66/R/server.R#L101

This should of course be `if (is.na(use_ssl))` instead, so an easy fix.

Other than that, it looks great! Just as I had in mind. Thanks again!

**Comment by datawookie** [comment]
Hi @lukasfeick-sw, I have fixed that typo. Thanks for spotting. Can you please confirm that you are happy with the changes? If so then I will merge. Thanks, Andrew.

**Comment by lukashaenjes** [comment]
@datawookie Works perfectly now, feel free to go ahead with the merge. Thanks! 🚀

**Comment by datawookie** [comment]
Cool. I have pushed version 0.7.16. It's available on GitHub but not CRAN because the latter is not currently accepting submissions. Thanks, Andrew.
