### ISSUE TITLE
Can not send email throu Apple iCloud SMTP

### ISSUE THREAD

**Issue by standera** [datawookie/emayili#157]
Even if the address and the password are correct the send function ends with a message: Request failed after 5 attempts.

**Comment by datawookie** [comment]
I can't help you without more information.

**Comment by standera** [comment]
I want to give more but do not know what might help. I am not this kind of expert. And calling the smtp(…) does not say more. Sorry.

Regards.
Miroslav Štandera

**Comment by datawookie** [comment]
I have no context for what you are trying to do except that you are using an Apple iCloud account. I don't have an account on that service. Without further information from you I'm afraid I can't help.
