### ISSUE TITLE
Troublesome onLoad behaviour

### ISSUE THREAD

**Issue by smartiing** [datawookie/emayili#158]
Hello, 

I am a big fan of the package that I use a lot. Thanks for the hard work. However, I don't like the fact that the .onLoad function set the option digits.secs = 3. It typically messes up with some formatting somewhere else in my code as it is something that will impact a lot of default R formatting. 

A simple Sys.time() will print 
- By default : "2024-09-25 18:13:00 CEST"
- After load : "2024-09-25 18:13:18.831 CEST"

Would you consider changing this ?

Thank you

**Comment by datawookie** [comment]
I would most certainly consider it. Why don't you make the change and submit a PR. I will happily merge your contribution.

**Comment by smartiing** [comment]
I'd be glad to make the change and submit a PR but I don't understand exactly what this would affect. It is mentioned (3bd660b) that it is used to have "Time displayed to millisecond precision" but I don't know where in the codebase. Could you give some direction ?

Would you go back for the time not being displayed to millisecond precision or should the code be modified to do it without the option being set globally ?

Thanks

**Comment by datawookie** [comment]
Just edit the `.onLoad()` function as mentioned in your original message and submit a pull request. You can also just fork a copy of the repository and make the change online in your copy and then create a pull request. No need to fiddle with Git of that's not your jam.
