### ISSUE TITLE
Return status from sending mail

### ISSUE THREAD

**Issue by EricGoldsmith** [datawookie/emayili#18]
This is such a small change, doesn't seem worth a PR, so documenting here.

Modify [this code](https://github.com/datawookie/emayili/blob/master/R/server.R#L66-L68):

```
   curl_fetch_memory(url, handle = h)

   close(con)
}
```

to this:

```
   res <- curl_fetch_memory(url, handle = h)

   close(con)

   invisible(res)
}
```

In order to return status info to the caller.

**Comment by datawookie** [comment]
Thanks, @EricGoldsmith! Good call. I've made the changes and pushed them on `dev`. Once we've nailed down the question of the CIDs I'll merge all of this into `master`.

**Comment by datawookie** [comment]
On another topic, I really appreciate your input on this project and I'd like to add you as a collaborator in the `DESCRIPTION` file. Would you be happy with that? If so, please send me your details. Thanks, Andrew.
