### ISSUE TITLE
URL included in message changes

### ISSUE THREAD

**Issue by gorkang** [datawookie/emayili#21]
I am trying to send emails with Qualtrics preformatted links for a group of participants. Everything works, except that the links are changed when the email is sent.

In this example, the link 
"https://website.com/XY_stuff?Q_DL=2a94hds4QmHP_9NaQ3odv_MLRP_9GNlEdOXL2q9&Q_CHL=gl"
becomes 
"https://website.com/XY_stuff?Q_DL*94hds4QmHP_9NaQ3odv_MLRP_9GNlEdOXL2q9&Q_CHL="

There are two unwanted changes in this case:  
* "=2a" becomes "*"
* "=gl" becomes "="

Here is a minimal working example [minus emails and password]:

```
library(emayili)
library(dplyr)

LINK = "https://website.com/XY_stuff?Q_DL=2a94hds4QmHP_9NaQ3odv_MLRP_9GNlEdOXL2q9&Q_CHL=gl"
FROM = "FROM_EMAIL_HERE"
TO = "TO_EMAIL_HERE"

email <- envelope() %>%
  from(FROM) %>%
  to(TO) %>%
  subject("test") %>%
  emayili::body(
    paste0(
      "LINK: ", LINK),
    type = "html") 
  
smtp <- server(host = "smtp.office365.com",
                          port = 587,
                          username = FROM,
                          password = THE_PASSWORD_HERE)
  
smtp(email, verbose = TRUE)
  
```

Thanks for the great package!

**Comment by gorkang** [comment]
Here a simple curl code that works fine:

```
library(emayili)
library(curl)
library(magrittr)

message <- paste0('From: "Myself" <', sender, '>
To: "You" <', recipients, '>
Subject: Hi!
Link: ', LINK)

recipients <- "TO_EMAIL_HERE"
sender <- "FROM_EMAIL_HERE"
username <- "FROM_EMAIL_HERE"
password <- THE_PASSWORD_HERE
send_mail(mail_from=sender, mail_rcpt=recipients, smtp_server = 'smtp.office365.com:587',
          message = message, username = username, password = password, use_ssl = TRUE)
```

**Comment by datawookie** [comment]
Hi @gorkang,

Thanks for bringing this issue to my attention. I'm busy looking into it now. The problem was how the quoted printable encoding was being handled.

I've pushed a fix on the `encoding` branch. Would you mind please testing? Thanks.

You can install from that branch using:

```
> devtools::install_github("datawookie/emayili", ref = "encoding")
```

Best regards,
Andrew.

**Comment by gorkang** [comment]
It works as expected! Thanks for the quick response! I will be using it a bit more in the next few days and let you know if something comes up.
