### ISSUE TITLE
*** caught segfault *** address (nil), cause 'unknown' when using inside a docker

### ISSUE THREAD

**Issue by kirovtome** [datawookie/emayili#23]
I have an 'unknown' issue when i try to send a smtp mail from a dockerized app.
1. The app is an API that will send an email on port 587 via STARTTLS when running a GET method. It's working on my local machine, but
2. I've dockerized the app, and mapped the port 443, so i can call GET method from Postman (for example). The issue here is the following:

> Rebuilt URL to: smtp://smtp.gmail.com:587/
> Trying 64.233.165.108...
> TCP_NODELAY set
> Connected to smtp.gmail.com (64.233.165.108) port 587 (#0)
< 220 smtp.gmail.com ESMTP y25sm8936760lfy.59 - gsmtp
> EHLO f3343a22938f
> 250-smtp.gmail.com at your service, [92.53.46.200]
> 250-SIZE 35882577
> 250-8BITMIME
> 250-STARTTLS
> 250-ENHANCEDSTATUSCODES
> 250-PIPELINING
> 250-CHUNKING
> 250 SMTPUTF8
> STARTTLS
> 220 2.0.0 Ready to start TLS
> Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
> successfully set certificate verify locations:
>   CAfile: /etc/ssl/certs/ca-certificates.crt
> CApath: /etc/ssl/certs
> SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
> Server certificate:
>  subject: C=US; ST=California; L=Mountain View; O=Google LLC; CN=smtp.gmail.com
>  start date: Dec  3 14:47:42 2019 GMT
>  expire date: Feb 25 14:47:42 2020 GMT
>  subjectAltName: host "smtp.gmail.com" matched cert's "smtp.gmail.com"
>  issuer: C=US; O=Google Trust Services; CN=GTS CA 1O1
>  SSL certificate verify ok.
> EHLO f3343a22938f
> 250-smtp.gmail.com at your service, [92.53.46.200]
> 250-SIZE 35882577
> 250-8BITMIME
> 250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
> 250-ENHANCEDSTATUSCODES
> 250-PIPELINING
> 250-CHUNKING
> 250 SMTPUTF8
> AUTH LOGIN
< 334 VXNlcm5hbWU6
> ZG9ja2VydGVzdDM3QGdtYWlsLmNvbQ==
> 334 UGFzc3dvcmQ6
> ZVY1UDhiaUomNSQ0
> 235 2.7.0 Accepted
> MAIL FROM:<tomekirov1@gmail.com>
> 250 2.1.0 OK y25sm8936760lfy.59 - gsmtp

> *** caught segfault ***
> address (nil), cause 'unknown'

> Traceback:
> 1: curl_fetch_memory("smtp://smtp.gmail.com:587", handle = h)
> 2: email.project.zip(user.email = user.list)
> 3: eval(ei, envir)
> 4: eval(ei, envir)
....
> 38: r$run(port = 80, host = "0.0.0.0")
> An irrecoverable exception occurred. R is aborting now ...
> Segmentation fault

3. It seems that it's failing only when calling the GET method from the docker container. If i run curl inside the docker container, the emails will be send successfully.

**Comment by datawookie** [comment]
Hi @kirovtome, this feels like the issue is not with `{emayili}` but with the way that the API is behaving inside the container.

Are you sure that there is a recipient address specified?

In your verbose output I see

```
MAIL FROM:tomekirov1@gmail.com
```

which indicates that the _from_ address has been set. I would also expect to see `RCPT TO` which would specify the recipient address.

The fact that you've also got `address (nil), cause 'unknown'` supports the idea that there is no recipient address.

I'll admit that a segfault is not the ideal behaviour in this scenario. I'll add in a test now which will generate an error if a recipient address is not specified.

Best regards,
Andrew.

**Comment by datawookie** [comment]
I've added a test to check if there is at least one recipient email address. Changes are on the `dev` branch at ec5ab518 if you want to test.

**Comment by datawookie** [comment]
@kirovtome I've just submitted an updated version of `{emayili}` to CRAN. Can you please test and see if your issue has been resolved?

**Comment by kirovtome** [comment]
@datawookie it's resolved, thanks!

**Comment by datawookie** [comment]
Great. Thanks for letting me know, @kirovtome.
