### ISSUE TITLE
Bolding/Underlining text in emails

### ISSUE THREAD

**Issue by benyamindsmith** [datawookie/emayili#24]
Hi there!

I have been playing around with your package and have really been enjoying how it works. 

Is there any way to bold/underline text sent in an email written? Or would I need a different package for that?

Thanks!

**Comment by datawookie** [comment]
Hi Banyamin.

How about using an HTML body like this:

```
envelope() %>%
  from(SMTP_USERNAME) %>%
  to(SMTP_USERNAME) %>%
  subject("HTML body") %>%
  html("<p><strong>Hello</strong>, <em>World</em>! Also <u>underline</u>.</p>") %>%
  smtp(verbose = TRUE)
```

Best regards,
Andrew.
