### ISSUE TITLE
Determining if Email has been successfully sent.

### ISSUE THREAD

**Issue by benyamindsmith** [datawookie/emayili#25]
Hi there, 

Just wondering if I want to send a blast to a list of emails. Will successfully sent emails be viewable in my sent folder (I'm using bluehost for context).

I'm wondering because I did send several emails but none of them are in my sent folder. However whenever I send it to myself (as a test)- its seen in my sent folder.

Would that be a good hueristic? 

Thanks!

**Comment by datawookie** [comment]
Hi, I don't think that this relates to {emayili}. It's more a function of your SMTP service. Probably not an unreasonable heuristic though, provided that the email addresses on the list are all specified as individual recipients. Regards, Andrew.
