### ISSUE TITLE
Adding Signature line in email

### ISSUE THREAD

**Issue by benyamindsmith** [datawookie/emayili#26]
I've tried sending some emails but my Email signature (put in gmail for this one) is not included inline. 

Do  I need to manually add it or is there a way to automatically include it?

 ```{r}

envelope()%>%
    from(sender)%>%
    to(reciever)%>%
    subject(subject_line)%>%
html(content=html_text)
```

**Comment by datawookie** [comment]
Hello again Benyamin, the email signature is handled by your email client. If you want to do this with {emayili} then you'll need to add it manually. This might be a reasonable idea for developing specific signature functionality though! Thanks, Andrew.
