### ISSUE TITLE
AWS smtp

### ISSUE THREAD

**Issue by riskcede** [datawookie/emayili#27]
Hi Andrew

I have moved hosting to AWS and are running R on an Ubuntu server there.

It seems Amazon is very strict on sending emails from their servers, so just using google smtp doesnt work.

Ive followed all the steps to setup their SES, Simple Email Serves, to use their own smtp server, but when running the emayili script it just stops at a certain point and then crashes. I have attached the output below?

I assume its a AWS setup issue, but does this output mean anything to you?

Thanks

Regards
Jan 

smtp <- server(host = "email-smtp.us-east-1.amazonaws.com",
               port = 465,
               username = “amazon_smtp_un",
               password = "amazon_smtp_pw")

email <- envelope() %>%
  from("info@riskcede.co.za") %>%
  to('jan@riskcede.co.za') %>%
  subject("Good morning report") %>%
  body('Hi')

smtp(email, verbose = TRUE)

Sending email to smtps://email-smtp.us-east-1.amazonaws.com:465.
* Rebuilt URL to: smtps://email-smtp.us-east-1.amazonaws.com:465/
*   Trying 18.214.81.247...
* TCP_NODELAY set
* Connected to email-smtp.us-east-1.amazonaws.com (18.214.81.247) port 465 (#1)
* found 133 certificates in /etc/ssl/certs/ca-certificates.crt
* found 401 certificates in /etc/ssl/certs
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: email-smtp.us-east-1.amazonaws.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: CN=email-smtp.us-east-1.amazonaws.com
* 	 start date: Tue, 18 Jun 2019 00:00:00 GMT
* 	 expire date: Sat, 18 Jul 2020 12:00:00 GMT
* 	 issuer: C=US,O=Amazon,OU=Server CA 1B,CN=Amazon
* 	 compression: NULL
< 220 email-smtp.amazonaws.com ESMTP SimpleEmailService-d-4N0BH6NI1 T5Kahd8yqgfwvx3uwc1P
> EHLO ip-172-31-3-23
< 250-email-smtp.amazonaws.com
< 250-8BITMIME
< 250-SIZE 10485760
< 250-AUTH PLAIN LOGIN
< 250 Ok
> AUTH LOGIN
< 334 VXNlcm5hbWU6
> QUtJQTVYNkZGRUs0SUEyNFdYV1c=
< 334 UGFzc3dvcmQ6
> Qkd6bCtNTFVUaXErWXNjbEZiQlErYW1La09pV2gvM2lyemR6bmgwY1FWTXo=

**Comment by datawookie** [comment]
Hi Jan,

I don't believe that the issue lies with AWS: my understanding is that GMail is blocking emails originating from EC2.

TBH I have not yet tried `{emayili}` with AWS email. I'll allocate some time and give this a try.

Thanks,
Andrew.

**Comment by galachad** [comment]
@riskcede I agree with @datawookie 

I'm using `emayili` with Amazon SES without any issue.

Regards,
Adam

**Comment by datawookie** [comment]
Thanks, @galachad! Could you help with any setup hints? Anything special you needed to do to get it working?

**Comment by datawookie** [comment]
Hi @riskcede, are you still having trouble with `{emayili}` on AWS?

Did you manage to verify your domain for SES (by adding the `TXT` record to your DNS settings)?

**Comment by datawookie** [comment]
@riskcede I never heard back from you, so I'm closing this issue. Feel free to reopen.

**Comment by riskcede** [comment]
Hi Andrew

Sorry I never replied, i was searching for an old email from you now and found this in my junkmail.

Yes, I can send emails from AWS now.

Im using tryCatch() to loop over email addresses that fail and i put a Sys.sleep() in my loop to make sure I dont send out too many emails in a given time period.

The script works now, next im going to try and do it with purrr and map to save it to the original list of email addresses.

Thanks again for this package you have developed. Its so easy to use (and install) and I use it a lot!

Regards
Jan

**Comment by datawookie** [comment]
Great to hear!
