### ISSUE TITLE
Installing emayili 

### ISSUE THREAD

**Issue by heeringa0** [datawookie/emayili#28]
Wonderful package that does not need Java! I got it running locally. 

I also tried to install this on the server. Installing from Github did not succeed, so I created   emayili_0.2.2_R_x86_64-pc-linux-gnu.tar.gz and tried to install with: install.packages("emayili_0.2.2_R_x86_64-pc-linux-gnu.tar.gz", repos = NULL, type = "source").

But this gave an error: '‘cannot read workspace version 3 written by R 3.6.2; need R 3.5.0 or newer’'. 

I cannot change the R version on the server. Is er there nevertheless any trick to solve this?

**Comment by datawookie** [comment]
Hi!

>  Installing from Github did not succeed...

Can you give me some idea how this failed? Is this how you tried to install?

```
> devtools::install_github("datawookie/emayili")
```

An alternative route to installing is somewhat more elaborate.

1. Download the ZIP archive from GitHub.
2. Unpack the archive.
3. Build a source distribution from the terminal. This will create `R CMD build emayili-master`.

```
$ R CMD build emayili-master/
```

4. Now install from R:

```
> install.packages("emayili_0.2.2.tar.gz", repos = NULL)
```

If neither of these approaches work for you, please provide additional information about how and where they failed and I can use that to help you figure out a solution.

Thanks,
Andrew.

**Comment by heeringa0** [comment]
Dear Andrew,

Thank you so much for your response!

I tried:
install.packages("emayili_0.2.2.tar.gz", repos = NULL)
and found that emayili depends on httr, and httr depends on openssl.
The installation of openssl went wrong, I got the message:

Configuration failed because openssl was not found. Try installing:
 * deb: libssl-dev (Debian, Ubuntu, etc)
 * rpm: openssl-devel (Fedora, CentOS, RHEL)
 * csw: libssl_dev (Solaris)
 * brew: openssl@1.1 (Mac OSX)

so I passed this to the maintainers of the server who are able to install this.

Thanks again, locally emayili works perfectly, I prefer this to mailR
since no Java is required.
Do you consider to deposit the package to CRAN?

Best regards,
Wilbert











Op ma 27 jan. 2020 om 08:39 schreef Andrew Collier <notifications@github.com

**Comment by datawookie** [comment]
Hi Wilbert,

Yeah, dependencies are always a problem. But I still think that this is better than Java! :)

Did you manage to get the server administrator to install the SSL library? Let me know if I can help with this.

And, yes, I submitted the package to CRAN and I'm waiting to hear back.

Thanks,
Andrew.

**Comment by heeringa0** [comment]
Hi Andrew,

Thanks for your message.
The server administrator has not installed the SLL library yet, after doing
the request it can take several weeks before they do it.
They use a Kubernetes system, which makes it more complicated to install
this, but it should non be impossible.
I will let you know my findings after they have installed the library.

Great that you submitted emayili to CRAN.

Best regards,
Wilbert



Op di 4 feb. 2020 om 14:54 schreef Andrew Collier <notifications@github.com

**Comment by heeringa0** [comment]
Hi Andrew,

The SLL library has been installed, so now I was able to install emayili.

Thanks for your help!

Best regards,

Wilbert


Op do 6 feb. 2020 om 11:30 schreef Wilbert Heeringa <wjheeringa@gmail.com>:

**Comment by datawookie** [comment]
Great news. Let me know how it goes.
