### ISSUE TITLE
emayili on R.3.6.x not working

### ISSUE THREAD

**Issue by csitter267** [datawookie/emayili#31]
I am working with the new version of R (3.6.2) and I can't install the library.
Is there a way, that emayili runs on that version?

**Comment by datawookie** [comment]
@csitter267 I'd love to help but you'll need to give me more information than that.

What goes wrong when you try to install the library? What error do you get? Please copy and paste the install log into this issue.

**Comment by csitter267** [comment]
> remotes::install_github("datawookie/emayili")
Fehler: Failed to install 'unknown package' from GitHub:
schannel: failed to receive handshake, SSL/TLS connection failed

**Comment by datawookie** [comment]
Looks like a networking problem to me. I've just run `remotes::install_github("datawookie/emayili")` and it installed 100% fine. Please try again.

Also you might find [this](https://stackoverflow.com/questions/46472724/why-schannel-fails-to-receive-handshake-from-the-server) thread has some helpful suggestions.
