### ISSUE TITLE
Issues with bare line feeds and UTF-8 encoding

### ISSUE THREAD

**Issue by pmoulos** [datawookie/emayili#32]
Hello and thanks for this wonderful user-friendly package!

I may have spotted a couple of issues:

1. When sending mail to MS Exchange servers, it bounces back (or ends in spam in the best case) because the mail headers (constructed essentially in ```format.mime()``` and elsewhere) are separated by ```\n``` (or ```<LF>```) instead of ```\r\n``` (or ```<CR><LF>```) as it seems that this is the standard SMTP protocol. More information can be found [here](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-6-11-in-exchange-online).

2. Some accidental argument order inconsistencies in ```body.R``` (namely in the ```text()``` and ```html()``` functions caused problems with UTF-8 encoding and possibly attachments. The arguments passed to ```mime()``` were in a different order than expected by ```mime()```.

I forked the package [here](https://github.com/pmoulos/emayili) and fixed (I believe) the above two issues. If you are happy I can make a PR.

Thanks again for all the work.

**Comment by datawookie** [comment]
Hi @pmoulos, thanks for this very helpful feedback. I became aware of the issue with MS Exchange this week but was not sure what the route cause was. Your help is definitely appreciated! I'll be looking at the package and resolving these issues early next week. Please feel free to make a PR in the meantime! Best regards, Andrew.

**Comment by datawookie** [comment]
Thanks for this @pmoulos! Please see comment on PR. Would be very happy to add you as contributor on package.
