### ISSUE TITLE
Error: token supplied to the function is invalid

### ISSUE THREAD

**Issue by gacolitti** [datawookie/emayili#35]
I'm trying to send an email on a Windows 10 machine in an enterprise context, but I get an error about an invalid token. 

``` r

library(curl)
library(emayili)
library(magrittr)

email <- envelope()
class(email)
#> [1] "envelope"

email <- email %>%
  from("myemail") %>%
  to("myemail") %>%
  subject("This is a test") %>%
  text("This is text")


smtp <- server(host = "mail.domain.com",
               port = 465,
               username = "user",
               password = "pwd")

smtp(email, verbose = TRUE)
#> Error in curl_fetch_memory(url, handle = h): schannel: next InitializeSecurityContext failed: SEC_E_INVALID_TOKEN (0x80090308) - The token supplied to the function is invalid
```

<sup>Created on 2020-03-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by datawookie** [comment]
Hi!

A quick Google reveals that this error is from the underlying `{curl}` package and most likely relates to a certificate issue. See [this](https://github.com/jeroen/curl/issues/127).

Regards,
Andrew.
