### ISSUE TITLE
Microsoft changes

### ISSUE THREAD

**Issue by DataStrategist** [datawookie/emayili#36]
Yesterday we recieved this alert from microsoft:

> This is an important communication about the future supported options for Outlook integration for Dynamics 365 and Power Apps.
>
> The Microsoft Dynamics 365 for Outlook integration (also known as Outlook COM add-in) is deprecated. Please plan to transition to the Dynamics 365 App for Outlook before October 1, 2020. Microsoft will continue to provide support, security and other critical updates to the Outlook COM add-in until October 1, 2020 but will not release any additional functionality beyond what has already been announced. For additional information about this change, please visit our blog.

Does this affect you?

**Comment by datawookie** [comment]
Thanks!

I don't anticipate that this will be an issue.
