### ISSUE TITLE
Content-type: multipart/related causing problems with Apple devices

### ISSUE THREAD

**Issue by EricGoldsmith** [datawookie/emayili#37]
Hey Andrew,

You've been busy :-) Nice to see this package on CRAN.

I'd been using a local fork since late November, and just pulled in all your changes today. Aside from some breaking changes to `attachment()` and `body()`, things looked good.

But, additional testing revealed the following issues:
- for emails with multiple image attachments, the images were showing up out of order in the MacOS mail.app
- for emails with *any* image attachments, the images were not visible in the iOS mail app.

Some experimentation traced the culprit to [this commit](https://github.com/datawookie/emayili/commit/8915cbf7a125e96bb672a41a4cce66fe9a7737b8), changing the Content-type on the outermost container from `multipart/mixed` to `multipart/related`. No explanation was given for the change.

Changing back to `multipart/mixed` resolved the issues, and restored prior functionality.

In case it's relevant, here's the pattern I'm using to construct emails:
```
mailResults <- function(recipients, subject, attachFilenames) {
  
  email <- envelope() %>%
    from("no-reply@blah.com") %>%
    to(recipients) %>%
    subject(sprintf("%s, %s", subject, lubridate::date(now()))) %>% 
    html(subject)
  
  for (i in seq_along(attachFilenames)) {
    email <- email %>%
      attachment(attachFilenames[i])
  }
.
.
.
```

I'm certainly no expert on MIME stuff, but the bit of digging I did ([here](https://en.wikipedia.org/wiki/MIME#Multipart_messages), [here](https://docs.microsoft.com/en-us/previous-versions/office/developer/exchange-server-2010/aa493937(v%3Dexchg.140)), [here](https://stackoverflow.com/questions/3902455/mail-multipart-alternative-vs-multipart-mixed)), seems to indicate that when using `multipart/related` additional ordering information is needed for the parts/attachments.

**Comment by datawookie** [comment]
Hi @EricGoldsmith,

Thanks for bringing this to my attention. I think that I was just trying out some options with `multipart/related` and they became a fixture.

I've reverted to `multipart/mixed` in the `dev` branch. Would you mind please installing and testing?

```
remotes::install_github(
    "datawookie/emayili",
    ref = "a52143359cb2575309c8e71afd6457416d1a68bb"
)
```

If you're happy with the revisions then I'll update the version on CRAN.

Thanks,
Andrew.

**Comment by EricGoldsmith** [comment]
Looks good here. 

Thanks,
Eric
