### ISSUE TITLE
Is it possible to install without RTools?

### ISSUE THREAD

**Issue by rdatasculptor** [datawookie/emayili#4]
Thanks for this very promising package!

Unfortenately I work on a restricted machine on whicht RTools is not allowed to be installed. (don't ask me why).
Is it possible to install the development version of curl and your package emayili without having to use Rtools?

**Comment by datawookie** [comment]
Hi @rdatasculptor,

I'm working in a Linux environment, so I have not come up against the RTools requirement. Can you please clarify: is this necessary to install the development version of `{curl}`?

Thanks,
Andrew.

**Comment by rdatasculptor** [comment]
yes it is. And also for emayili, as it needs curl. 
But I realise this is not the right place to ask since it is mainly a curl issue. I will close this one.

**Comment by datawookie** [comment]
Right. I suspected that the requirement might be for `{curl}`. I've submitted a pull request on that development branch and I'm hoping that @jeroen will merge it at some stage and that it will propagate to CRAN. At that point I think you should be good.

**Comment by rdatasculptor** [comment]
Thanks for submitting!
