### ISSUE TITLE
Unable to add a variable name as an input in the  "attachment" function  of emayili

### ISSUE THREAD

**Issue by natasha108** [datawookie/emayili#47]
Hi There

I  would like my attachment input from this package to allow for  a variable input also unfortunately it only accepts a path of the attachment file.
I used a paste() as the attachment input function but it comes up with an error stating the file can't be found.
This will occur naturally as you are changing a path input to text

Here is a snapshot of what I am trying to do:

```
myname <-"Natasha"

email <- envelope() %>%
  from("natasha@gmail.com") %>%
  to("test@gmail.com") %>%
  subject(paste("My name is :", myname)) %>%
  attachment(paste("~/test_report.html","- " ,myname), disposition = "attachment")
smtp(email, verbose = TRUE)
```

I will email directly with code that works!

Thanks,
Natasha

**Comment by datawookie** [comment]
Hi @natasha108, I've added a `name` parameter to the `attachment()` function which should do what you want. Please update to the current version on the `master` branch. Here's an example:

```
path_cats    <- tempfile(fileext = ".jpg")

download.file("https://bit.ly/2P4LUO8", path_cats, quiet = TRUE)

msg <- envelope() %>%
  attachment(path_cats, type = "image/jpeg") %>%
  attachment(path_cats, name = "cat.jpg", type = "image/jpeg")
```

The message will have two attachments (both of the are the same file). The first attachment will have the "local" name (which is a random string of characters) and the second one will have the name "cat.jpg".

Let me know if this works for you and we can close this issue. Thanks, Andrew.

**Comment by natasha108** [comment]
Hi @datawookie , thank you for looking into this issue. Success!! The updates to the package perfectly resolves the issue.

I am now able to mail out reports with variable names

Thanks :)
Natasha
