### ISSUE TITLE
Issues with using the gmail smtp

### ISSUE THREAD

**Issue by willglanville** [datawookie/emayili#5]
Hi -

Thanks for making the package.

I'm having trouble running the gmail smtp. R gets to the following position then crashes. Any ideas?

![gmail_error](https://user-images.githubusercontent.com/12036272/58635704-721b6e00-82e6-11e9-93ad-a1b0825685fe.png)

**Comment by datawookie** [comment]
Hi @willglanville, thanks for the email. Very happy to help. I'd need some context though. Can you please include a minimal example which illustrates the problem you are having? Obviously don't include any credentials! Thanks, Andrew.

**Comment by willglanville** [comment]
Hi Andrew - 

Thanks for the reply.

Running the following. I've also changed the access permissions in gmail as per issue #2 

`
library(emayili)
library(dplyr)

email <- envelope() %>%
  from([myemailaddress]) %>%
  to([myotheremailaddress]) %>%
  subject("This is a plain text message!") %>%
  body("Hello!")

smtp <- server(host = "smtp.gmail.com",
  port = 465,
  username = [mygmailaddress],
  password = [app password for my gmail])

smtp(email, verbose = TRUE)

`
Thanks,

Will

**Comment by datawookie** [comment]
Hi Will,

Sorry, but I've been unable to reproduce this error locally, which makes it pretty difficult for me to debug.

I see that you're on a Windows machine. Not sure if this is possible for you, but have you tried sending an email using `curl` from the command line as described [here](https://datawookie.netlify.com/blog/2019/05/emayili-sending-email-from-r/). Knowing whether or not that works may well help us unlock this puzzle.

Best regards,
Andrew.
