### ISSUE TITLE
construct entire email from envelope()

### ISSUE THREAD

**Issue by mkoohafkan** [datawookie/emayili#50]
Sometimes you have all the parts of an email ready to go, and you just want to construct the whole thing at once rather piping to calls of `from()`, `to()`, `subject()`, etc. It would be nice if `envelope()` could optionally accept these parts and construct in one go, something like:

```r
envelope(
  from = "me@address.com",
  to = c("someone@address.com", "another@address.com"),
  subject = "an email",
  text = "stuff",
  ...
)
```
where any of those arguments could be omitted and later added with the appropriate function call. This would allow users to use `do.call()` or `pmap` to construct emails.

**Comment by datawookie** [comment]
This is a great idea. I'll implement it now.

**Comment by datawookie** [comment]
Hi @mkoohafkan, I've implemented this feature on the `dev` branch. Do you want to give it a try and let me know if it does what you want? If you're happy then I'll merge into `master`. Thanks, Andrew.

**Comment by mkoohafkan** [comment]
Works great! I might suggest adding arguments `cc`, `bcc` and `reply` as well. I guess it doesn't make sense to add an `attachment` argument since there are a number of additional parameters required... although I guess it could take a list, e.g. `envelope(attachment = list("file.png", cid = "picture", disposition = "inline")).` I haven't used `header()` directly yet so I don't know if it would make sense to add a `header` argument.

**Comment by datawookie** [comment]
Good call. We'll add those three arguments now.

I'm hesitant to add attachments and header items right now though. Let's see how this works out. If there's need for either of those we can add them later.

**Comment by datawookie** [comment]
Hi @mkoohafkan, my colleague @Matt-dD implemented these features. They are now available on the `master` branch. Would you mind testing?

**Comment by mkoohafkan** [comment]
@datawookie @Matt-dD I just tested it, works great!

**Comment by matt-denni** [comment]
@mkoohafkan that's great news.  Thanks very much for testing!

**Comment by datawookie** [comment]
Perfect! Thanks, @mkoohafkan.
