### ISSUE TITLE
Inline image in html body

### ISSUE THREAD

**Issue by gfspiteri** [datawookie/emayili#53]
Hi, thanks for the excellent package. It's really great not having to worry about JAVA dependencies. I am trying to send an email with an inline image in an html body but image keeps turning blank. If I attach the same image then I get it fine as an attachment (but not in the body of the email). Am I doing something wrong?

```
library(emayili)
library(dplyr)

html <- '<html><body style="font-family:calibri;">
<p><i>Email text</i></p>
<img src="C:/Users/xxxx/Documents/branding.png"></body></html>
'

email <- envelope()

email <- email %>%
  from("<xxxxx@xxxxx.xx>") %>%
  to("xxxx@gmail.com") %>% 
  subject("This is an html message!") %>%
  html(html) %>%
  attachment(path = "C:/Users/xxxx/Documents/branding.png")

smtp <- server(host = "xxxxxxx",
               port = 25,
               insecure = FALSE,
               reuse = FALSE)
smtp(email, verbose = TRUE)
```

**Comment by datawookie** [comment]
Hi, thanks for bringing this to my attention. I'll take a look. Best regards, Andrew.

**Comment by gfspiteri** [comment]
Many thanks – let me know if you want me to test anything,
Best
Gianfranco

**Comment by gfspiteri** [comment]
I was just trying some alternative options to include images inline using for example img_txt <- base64encode("branding.png") and then including the results in the img src tag: <img src="data:image/png;base64,', img_txt, '

In the resulting email it lookgs like the html() function crops the html produced so the image ends up not being produced. Could it be related to the original issue?

**Comment by datawookie** [comment]
Hi @gfspiteri, sorry it's take so long to get back to you on this. I've just tried this and confirmed that it works. I've amended the `README` file to document the process. Currently only on the `dev` branch. Please take a look and confirm that it works for you. The updated `README` can be found here: https://github.com/datawookie/emayili/blob/dev/README.md#adding-an-inline-image. Thanks, Andrew.

**Comment by gfspiteri** [comment]
Hi @datawookie I tried your code but it still won't work. The example in the `README` won't work. Even something this simple won't work:

```
html_body <- '<p>Taken from wikpedia</p>
  <img src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUA
    AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO
        9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Red dot" />'

email <- envelope()

email <- email %>%
  from("xxx@gmail.com") %>%
  to("xxx@gmail.com") %>% 
  subject("This is an html message!") %>%
  html(html_body) 

smtp <- server(host = "xxxx",
               port = 25,
               insecure = FALSE,
               reuse = FALSE)

smtp(email, verbose = TRUE)
```

If I look at `email$parts[[1]]$body` I see `=3D` added in. Not sure if that has to do with anything?

`[1] "<p>Taken from wikpedia</p>\n  <img src=3D\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUA\n    AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO\n        9TXL0Y4OHwAAAABJRU5ErkJggg=3D=3D\" alt=3D\"Red dot\" />"`

**Comment by gfspiteri** [comment]
Tried again - seems the problem is Gmail. It works on my work email but not visible in Gmail. In the end @AdrianProdan helped and we used an attachment and `CID:`.

```
html <- '<html><body style="font-family:calibri;">
<p><i>Email text</i></p>
<img src="cid:image"></body></html>
'

email <- envelope()

email <- email %>%
  from("xx@gmail.com>") %>%
  to("xx@gmail.com") %>%
  subject("This is an html message!") %>%
  html(html) %>%
  attachment(path = "C:/Users/xx/Documents/branding.png", cid = "image")
```

**Comment by datawookie** [comment]
Ah! I didn't realise that the issue was GMail. Otherwise I would have tested there. Thanks for this. Have updated the `README` to include two options.
