### ISSUE TITLE
Export message() function?

### ISSUE THREAD

**Issue by okhoma** [datawookie/emayili#54]
Can you, please, export `message()`? It does look like a method of class `envelope()` (something like `as.character.envelope()`). I am currently using it with `:::`, which is not very nice :)

**Comment by datawookie** [comment]
Hi!

This is a good suggestion. I've implemented a `as.character.envelope()` function in the `email-to-character` branch. Would you mind testing and confirming that it does what you want? In principle I might use this to replace `message()`.

I'm rather intrigued by how/why you are using this in application code. Having a better understanding of the use cases would definitely help me to support this feature better.

Best regards, Andrew.

**Comment by okhoma** [comment]
Thank you, Andrew. My use case is that I want to get SMTP error code and message in addition to curl error, because, too often curl error does not provide any additional information. I did that by providing my own `debugfunction` which checks  strings received from SMTP server and stores any error responses in the last message. However, the problem is that for it to work I must have `verbose = TRUE`, but it causes additional messages `Sending email to` and `Uploaded %d bytes ...`, which I do not need. To get rid of these additional messages I have changed my code to use `curl::curl_fetch_memory()` directly and to avoid building message I reuse `emayili::message()` for the envelope that I have created.

**Comment by datawookie** [comment]
Aha! Okay, I think I understand. Do you think that it would be worthwhile building this functionality into `{emayili}`?

**Comment by okhoma** [comment]
I would rather say that it should be part of `curl` package. But if it was implemented in `{emayili}` that would reduce the amount of code on my side.

**Comment by datawookie** [comment]
Understood.

In the meantime though can you please check out the changes that I have made and let me know whether they resolve your problem? Thanks.

**Comment by okhoma** [comment]
Hi, Andrew. I've checked the branch and it works exactly as I need it. Thank you.

**Comment by datawookie** [comment]
Excellent. I've pushed the new version (0.4.4) to CRAN.

Thanks for this suggestion.

**Comment by okhoma** [comment]
Thank you!
