### ISSUE TITLE
library(emayili) works great from RStudio and interactive commandl line but fails in crontab

### ISSUE THREAD

**Issue by ikohane** [datawookie/emayili#59]
I followed instructions and have had **no** problems executing from RStudio and running the script using Rscript from the bash command line (mac os X). But when I run it from crontab I get the connection errors you see below.

Isaac Kohane

Sending email to  smtps://p3plcpnl0846.prod.phx3.secureserver.net:465/ .
  Trying 50.62.177.159...
TCP_NODELAY set
Immediate connect fail for 50.62.177.159: Host is down
Closing connection 0
Error in curl_fetch_memory(smtp_server, handle = h) : 
  Couldn't connect to server
Calls: smtp -> send_mail -> curl_fetch_memory
Execution halted

**Comment by datawookie** [comment]
Hi @ikohane, are you still having trouble with this? Would like to sort it out for you because this is one of the typical applications where I use `{emayili}`. Thanks, Andrew.

**Comment by datawookie** [comment]
Okay, I'm going to presume that this issue is resolved for you. If you're still having trouble, please don't hesitate to reopen.
