### ISSUE TITLE
SMTP Authentication using client certificate without username and password

### ISSUE THREAD

**Issue by Alex089** [datawookie/emayili#60]
For my use case, I would like to verify to the smpt server not with a username and password, but only with a client certificate. I wanted to ask if this is supported somehow or if there is as workaround?

**Comment by datawookie** [comment]
Hello Alexander.

**Comment by Alex089** [comment]
Hello! ; )

**Comment by datawookie** [comment]
Hi @Alex089, I'd like to work on this feature. However, I don't have access to an email account where I can authenticate using a client certificate. So I'm going to need your help for testing. Can you please tell me more about your setup? What email service are you using? Thanks, Andrew.

**Comment by datawookie** [comment]
Hi @Alex089, since I didn't hear back from you I'm going to close this issue. Please reopen when you have time to debug this with me. Thanks, Andrew.
