### ISSUE TITLE
Script ends after successfully sent an email (gmail), without executing the rest of the script

### ISSUE THREAD

**Issue by kenkoonwong** [datawookie/emayili#61]
Hi, I created a list of birthdays, to automatically wish the person who has the birthday that day and also to remind others that it's this person's birthday by creating 2 smtp. Also instead of sending mass email all at once, I used for loop to send it individually. The code looks like this 

```
# special email to the particular person
email <- emayili::envelope() %>%
  from(from) %>%
  to(to) %>%
  subject("") %>%
  emayili::text(special_text) 

smtp <- server(host = "smtp.gmail.com",
               port = 465,
               username = username,
               password = password)

smtp(email, verbose = TRUE)
Sys.sleep(11)

#email reminder to others
to <- cellphone %>%
  filter(last_name != !!last_name) %>%
  pull(cell)

for (i in to) {
  email <- emayili::envelope() %>%
    from(from) %>%
    to(i) %>%
    subject("") %>%
    emayili::text(other_text) 
  
  smtp <- server(host = "smtp.gmail.com",
                 port = 465,
                 username = username,
                 password = password)
  
  
  smtp(email, verbose = TRUE)
  
  Sys.sleep(11)
  
}
```
It was only able to send the first email to the special person, not the rest. But when I tried it on smtpbucket, it worked. Thanks!

**Comment by datawookie** [comment]
Hi @micceee, can you please provide more information on what did (or didn't) happen when you ran the script on smtp.gmail.com? Were there errors? Was the outgoing email accepted by the SMTP server? If you didn't get an error and the code works with smtpbucket then I suspect that the issue lies with Gmail and not with `{emayili}`. But let's figure this out! Thanks, Andrew.

**Comment by kenkoonwong** [comment]
Thanks for the response! Yes, I think you're right, it's not emayili, it's gmail. Here is the message when I run the script.

```
Sending email to  smtps://smtp.gmail.com:465 .
Error in rawToChar(rawConnectionValue(log)) :
  embedded nul in string: 'Expire in 0 ms for 6 (transfer 0x33a70f8)\nExpire in 10000 ms for 2 (transfer 0x33a70f8)\nExpire in 1 ms for 1 (transfer 0x33a70f8)\nExpire in 0 ms for 1 (transfer 0x33a70f8)\nExpire in 1 ms for 1 (transfer 0x33a70f8)\nExpire in 0 ms for 1 (transfer 0x33a70f8)\nExpire in 0 ms for 1 (transfer 0x33a70f8)\nExpire in 1 ms for 1 (transfer 0x33a70f8)\nExpire in 0 ms for 1 (transfer 0x33a70f8)\nExpire in 0 ms for 1 (transfer 0x33a70f8)\nExpire in 1 ms for 1 (transfer 0x33a70f8)\nExpire in 0 ms for 1 (transfer 0x33a70f8)\nExpire in 0 ms for 1 (transfer 0x33a70f8)\nExpire in 1 ms for 1 (transfer 0x33a70f8)\nExpire in 0 ms for 1 (transfer 0x33a70f8)\nExpire in 0 ms for 1 (transfer 0x33a70f8)\nExpire in 1 ms for 1 (transfer 0x33a70f8)\nExpire in 0 ms for 1 (transfer 0x33a70f8)\nExpire in 0 ms for 1 (transfer 0x33a70f8)\nExpire in 1 ms for 1 (transfer 0x33a70f8)\nExpire in 0 ms for 1 (transfer 0x33a70f8)\nExpire in 0 ms for 1 (transfer 0x33a70f8)\nExpire in 1 ms
Calls: smtp -> cat -> rawToChar
Execution halted
```

**Comment by datawookie** [comment]
Could you please move the call to `server()` outside of the loop? You only need to call this once to establish a connection.

```
smtp <- server(host = "smtp.gmail.com",
               port = 465,
               username = username,
               password = password)

for (i in to) {
  emayili::envelope() %>%
    from(from) %>%
    to(i) %>%
    subject("") %>%
    emayili::text(other_text)  %>%
    smtp(verbose = TRUE)

  Sys.sleep(11)
}
```

**Comment by kenkoonwong** [comment]
Tried it, same problem. I even tried adding 

```
print("Did this pass?")
}
```

after the first `smtp` but it won't continue to run the entire script after the first `smtp`. Meaning I do not see "Did this pass?" after the first email (to the special person , without loop) was sent.

**Comment by datawookie** [comment]
I wasn't suggesting that this would fix the issue, just that it was better practice. Let me try this out locally.

**Comment by datawookie** [comment]
Hi @micceee, I wrote a short [blog post](https://datawookie.dev/blog/2021/02/emayili-sending-birthday-messages/) which details the approach I would take for this. All of the code has been tested with my Gmail account and it works. Feedback most welcome. Thanks, Andrew.

**Comment by kenkoonwong** [comment]
awesome! I'll check it out on my system. when i tinker around with curll:send_email yesterday it worked just fine with for loop. I do wonder if your best practice suggestion might have some pointers there with regards to calling smtp x 1 and perhaps piping envelope + message to smtp as opposed to assigning envelope to a variable. Thanks! I'll keep you posted

**Comment by kenkoonwong** [comment]
Thanks for doing this buddy. I don't know why when I did these

```
SMTP_USERNAME = Sys.getenv("this_is_my_username")
SMTP_PASSWORD = Sys.getenv("thisismypassword")
SMTP_SERVER   = Sys.getenv("smtp.gmail.com")
SMTP_PORT     = Sys.getenv("465")
```

all the variables above actually returned as empty variables?

```
> SMTP_USERNAME
[1] ""
```

Thoughts?

**Comment by datawookie** [comment]
Ah, no problem.

You need to actually set these variables in your environment. Probably the simplest way to do this would be to create an `.Renviron` file in the root of the repository.

```
SMTP_USERNAME=micceee@gmail.com
SMTP_PASSWORD=CMp643abjzGLCXmJGX3IW2Vr
SMTP_SERVER=smtp.gmail.com
SMTP_PORT=465
```

You need to restart your session in order for these changes to apply.

The nice thing about this approach is that you don't embed these parameters in your script, which means you can submit to version control with no worries.

**Comment by datawookie** [comment]
Hi @micceee, since I have not heard anything further from you, I'm assuming that this issue is resolved. Please feel free to reopen if you are still having trouble. Thanks, Andrew.
