### ISSUE TITLE
curl send_mail dependency

### ISSUE THREAD

**Issue by vinhdizzo** [datawookie/emayili#65]
Hi,

Thanks for the package.  Starting to use it, and ran into the following error:

```{r}
> smtp(out_email)
Error in send_mail(mail_from = msg$header$From, mail_rcpt = recipients,  : 
  could not find function "send_mail"
```

After some research, I learned that `send_mail` comes from the [curl](https://cran.r-project.org/package=curl) package, which doesn't have this function until version 4.0.0.  Could I suggest you specify 4.0.0 as the minimum version for `curl` in your `DESCRIPTION` file in order in order to get the package to install correctly?  Thanks.

**Comment by datawookie** [comment]
Hi @vinhdizzo, thanks for the excellent suggestion. Resolved in f02f1f5aa75ec26f6534f787b6d49aa70dfbb8ab.
