### ISSUE TITLE
"Name <name@domain.org>" Syntax Problem or Feature Request?

### ISSUE THREAD

**Issue by davesides** [datawookie/emayili#67]
Thanks for creating the package - nice solution!

When I try to include a "name" along with the email address I'm seeing an error come back from AWS SES. I've tried various syntax variations. Is it a new feature request for emayili or do you have a syntax suggestion?

```
email <- envelope() %>% 
  from("My Name <my.name@domain.org>") %>% 
  to(email_to) %>% 
  cc(email_cc) %>% 
  subject("Subject") %>% 
  text("Body of email.") %>% 
  attachment(log_file) %>% 
  attachment("error.log")

smtp <- server(host = email_endpoint,
               port = email_wrapper_port,
               username = email_username,
               password = email_pwd,
               insecure = FALSE,
               reuse = FALSE)

smtp(email, verbose = TRUE)
```
[edited content for possible sensitive information - see last couple of lines]

Sending email to smtps://<amazon url>.
Hostname in DNS cache was stale, zapped
  Trying <ip address>
TCP_NODELAY set
Connected to <amazon url>
220 <amazon url> ESMTP SimpleEmailService-<amazon string>
EHLO Machine-Name
250-<amazon url>
250-8BITMIME
250-AUTH PLAIN LOGIN
250 Ok
AUTH PLAIN
334 Ok
<amazon string>
235 Authentication successful.
MAIL FROM:<My Name <my.name@domain.org>>
553 **<My Name <my.name@domain.org> Invalid email address.**
MAIL failed: 553
QUIT

**Comment by datawookie** [comment]
Hi @davesides, at present this does not work with `{emayili}`. However, I'll add this feature to my backlog and sort it out in the next few days. Best regards, Andrew.

**Comment by datawookie** [comment]
Hi @davesides,

I've made a small tweak to `{emayili}` which should now handle this case. Would you mind testing it before I update CRAN?

The fix is on the `pretty` branch which you can install as follows:

```
remotes::install_github("datawookie/emayili@pretty")
```

Please let me know if this works for you. Or, if not, what problem you run into.

Thanks, Andrew.

**Comment by davesides** [comment]
Hi Andrew,

Appreciate the change! Away until June 10th. Will test around then. Thanks.

David

On Fri, Jun 4, 2021, at 11:10 PM, Andrew Collier wrote:
> 

> Hi @davesides <https://github.com/davesides>,

> I've made a small tweak to `{emayili}` which should now handle this case. Would you mind testing it before I update CRAN?

> The fix is on the `pretty` branch which you can install as follows:

> ***@***.***")
`

**Comment by davesides** [comment]
First I tried the code using the current CRAN version to make sure it worked with the basic to("my.name@domain.com"). No problem.

I then did a Clear Workspace and Restart R. (In RStudio)

When I pulled down the changed version as you directed and ran it with the simple "my.name@domain.com" it behaved as follows:

Sending email to smtps://email-smtp.us-west-2.amazonaws.com:465/.
Error: Request failed after 5 attempts
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning messages:
1: In handle_setopt(h, ...) : restarting interrupted promise evaluation
2: In handle_setopt(h, ...) : restarting interrupted promise evaluation
3: In handle_setopt(h, ...) : restarting interrupted promise evaluation
4: In handle_setopt(h, ...) : restarting interrupted promise evaluation
> rlang::last_error()
<error/purrr_error_rate_excess>
Request failed after 5 attempts
Backtrace:
 1. emayili:::smtp(email, verbose = TRUE)
 2. purrr:::send_mail(...)
 3. purrr::rate_sleep(rate, quiet = quiet)
 4. purrr:::stop_rate_excess(rate)
Run `rlang::last_trace()` to see the full context.
> rlang::last_trace()
<error/purrr_error_rate_excess>
Request failed after 5 attempts
Backtrace:
    x
 1. \-emayili:::smtp(email, verbose = TRUE)
 2.   \-purrr:::send_mail(...)
 3.     \-purrr::rate_sleep(rate, quiet = quiet)
 4.       \-purrr:::stop_rate_excess(rate)

To confirm it's not the more sophisticated way that works I then tried using to("My Name \<my.name@domain.com\>") with the same result.

Let me know if you want me to try something else or need additional information. Thanks.

**Comment by datawookie** [comment]
Thanks, @davesides, for the detailed error report. I'll get onto this ASAP.

**Comment by datawookie** [comment]
Hi @davesides, thanks for your patience. I took a look at this today and found that it was a dependency problem (needed to include `{stringr}` rather than just `{stringi}`). Would you mind trying again, please? Just install from the same location. Thanks, Andrew.

**Comment by datawookie** [comment]
Hi @davesides, did you manage to test this? Thanks, Andrew.

**Comment by davesides** [comment]
Hi Andrew,

Been away. Should have time today or tomorrow.

David

**Comment by davesides** [comment]
The following in from() and to() works correctly for me now:

"name@domain.com"
"My Name \<name@domain.com\>"

Both from the RStudio environment and when called from RScript.

Used AWS smtp for sending. Received into Office 365 email.

Thank you!

**Comment by datawookie** [comment]
Great! Will be pushing this to CRAN today.
