### ISSUE TITLE
Create a HTML body from an existing HTML file

### ISSUE THREAD

**Issue by freuerde** [datawookie/emayili#70]
Is it possible to send an email with a HTML body using an existing HTML file created by rmarkdown?
Thanks a lot.

**Comment by datawookie** [comment]
Hi @freuerde,

I've implemented the changes required to make this work. Please can you test by installing from GitHub?

```
remotes::install_github("datawookie/emayili")
```

Let me know if this works for you and I'll merge into `master` and then push to CRAN.

Thanks, Andrew.

**Comment by freuerde** [comment]
Hi Andrew,

Wow, that was fast. It works pretty well using it as follows:
email %>% html(path_to_html_file)

Thanks a lot for fixing it.
Dennis

**Comment by datawookie** [comment]
Great.

> pretty well

If you have any suggestions for how we can get it working _very_ well, please let me know.

Also, thanks very much for the feedback. Suggestions like this really do improve the package. Keep them coming!

**Comment by freuerde** [comment]
Sorry for my wording. The fix made the function indeed excellent. The function is now more flexible (regarding the RMarkdown generated HTMLs), easy to use (how I showed in the code example above) and works fine without the need for Java (what is an important point for me).

**Comment by datawookie** [comment]
:) No problem! Super happy to know that it's working for you. As I mentioned before, if you have other suggestions for how I can make `{emayili}` more convenient, please let me know.
