### ISSUE TITLE
 server closed abruptly 

### ISSUE THREAD

**Issue by ceciliacronemberger** [datawookie/emayili#71]
My script sending emails with Emayili was working fine and suddenly it stopped working. Here is the error log:

Sending email to smtps://smtp.gmail.com:465/.
Found bundle for host smtp.gmail.com: 0x24b7a0ba4a0 [serially]
Re-using existing connection! (#1) with host smtp.gmail.com
Connected to smtp.gmail.com (2800:3f0:4003:c00::6d) port 465 (#1)
MAIL FROM:<xxxxxx@gmail.com>
421 4.7.0 Try again later, closing connection. (MAIL) g4sm240722pgs.42 - gsmtp
MAIL failed: 421
QUIT
schannel: server closed abruptly (missing close_notify)
Closing connection 1
schannel: shutting down SSL/TLS connection with smtp.gmail.com port 465
  Trying 2800:3f0:4003:c02::6d...
TCP_NODELAY set
Connected to smtp.gmail.com (2800:3f0:4003:c02::6d) port 465 (#2)
220 smtp.gmail.com ESMTP g19sm112160pjl.25 - gsmtp
EHLO DESKTOP-VE1RNE6
250-smtp.gmail.com at your service, [2804:18:581a:910f:31ae:b3fd:4149:9b7c]
250-SIZE 35882577
250-8BITMIME
250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
AUTH PLAIN
334
bmVvdHJvcGljYWwubmV0d29ya3NAZ21haWwuY29tAG5lb3Ryb3BpY2FsLm5ldHdvcmtzQGdtYWlsLmNvbQB2YWlkYXJjZXJ0bzIwMjE=
235 2.7.0 Accepted
MAIL FROM:<xxxxx@gmail.com>
421 4.7.0 Try again later, closing connection. (MAIL) g19sm112160pjl.25 - gsmtp
MAIL failed: 421
QUIT
schannel: server closed abruptly (missing close_notify)
Closing connection 2

<error/purrr_error_rate_excess>
Request failed after 5 attempts
Backtrace:
    x
 1. \-emayili:::smtp(email, verbose = TRUE)
 2.   \-purrr:::send_mail(...)
 3.     \-purrr::rate_sleep(rate, quiet = quiet)
 4.       \-purrr:::stop_rate_excess(rate)

**Comment by ceciliacronemberger** [comment]
The script works for a while (maybe a couple of minutes) and then the server closes abruptly. The first time it sent 85 emails and stopped. the second time it sent 88 emails defore stopping.

**Comment by datawookie** [comment]
Hi @ceciliacronemberger,

I don't think that this is a problem with `{emayili}`. You appear to be sending a bunch of emails to the server with (I'm guessing) little or no delay between each message. I suspect that the server is simply shutting you out.

There's already a retry functionality (see the `Request failed after 5 attempts` message in your output) which uses exponential backoff. I've added a `pause_base` parameter to the `server()` function which allows you to extend the delay between retries. If my suspicions are correct, then increasing this delay might get you around the server temporarily blocking further messages.

```r
smtp <- server(
  host = SMTP_SERVER,
  pause_base = 5
)
```

The default base delay is 1 second. Increasing it to 5 seconds will give the server more time to recover before you try again.

Another thing that I'd suggest is to build in a small delay to the loop which you are using to submit the messages. Always good practice to be polite with a server and not bombard it with a series of requests in short succession.

You can install the updated package using:

```r
remotes::install_github("datawookie/emayili", ref = "2c7dd0d7e34d18c905f94a1ff44aba7403477e0c")
```

When I hear back from you I'll submit the changes to CRAN.

Hope that this helps! Best regards, Andrew.
