### ISSUE TITLE
The From field leads to a Sender Identity error

### ISSUE THREAD

**Issue by nicolasfguillaume** [datawookie/emayili#73]
In version 0.4.16, the From field is modified to a list and this leads to a Sender Identity error.

In version 0.4.15 I had:

```
To: z@abc.com
From: noreply@abc.com
Cc: x@abc.com, y@abc.com
Subject: Test
X-Mailer: {emayili}-0.4.15 
MIME-Version: 1.0 
Content-type: multipart/mixed; boundary="****************" 
```

Now I have (the From field is different):

```
To: z@abc.com
From: list(email = "noreply@abc.com", display = NA) 
Cc: x@abc.com, y@abc.com
Subject: Test
X-Mailer: {emayili}-0.4.16 
MIME-Version: 1.0 
Content-type: multipart/mixed; boundary="****************" 
```

Which eventually leads to this error:

```
The from address does not match a verified Sender Identity. Mail cannot be sent until this error is resolved. Visit https://sendgrid.com/docs/for-developers/sending-email/sender-identity/ to see the Sender Identity requirements
```

**Comment by datawookie** [comment]
Hi @nicolasfguillaume, thank you for bringing this to my attention. Fixed in 579c17713129d28855b47ed96180c7250e0564b2. Would you mind testing from GitHub, please? If you can confirm that I've sorted out the reversion then I'll push to CRAN. Best regards, Andrew.

**Comment by nicolasfguillaume** [comment]
Hi Andrew, yes your commit fixed it. Many thanks!

**Comment by datawookie** [comment]
Magic. I'll push that to CRAN on 1 September 2021, since the CRAN maintainers are on holiday until then.
