### ISSUE TITLE
"From" Address not formatting correctly

### ISSUE THREAD

**Issue by jonmichael-caldwell** [datawookie/emayili#74]
Hi all,

when using a simple send mail function as below, the resulting email has an incorrectly formatted sender address. The to, subject, body, all appread correct. I can't seem to figure out how to get sender address to appear correctly.

```
sendemail <- function(subject, message, to){
  email <- envelope()
  email <- email %>% 
    from("person@domain.com") %>%
    to(to) %>%
    subject(subject) %>%
    text(message)
  
  smtp <- server(host = "smtp.gmail.com",
                 port = 465,
                 username = "myemail@gmail.com",
                 password = "mypassword",
                 reuse = FALSE)
  smtp(email, verbose = TRUE)
}
```

The resulting email sends and appears correctly except the sender is
"email = person@domain.com, display = NA"

If I change the code to
`...
from("A Person <person@domain.com>")`

the the resulting email shows the sender as

"email = person@domain.com, display = A Person"

....any ideas?

**Comment by datawookie** [comment]
Hi @jonmichael-caldwell, thanks for getting in touch about this issue. It's already been resolved (https://github.com/datawookie/emayili/issues/73) and you can install the fixed version directly from GitHub. Unfortunately, I won't be able to push the update to CRAN until their team comes back from the Summer holidays on 1 September 2021. Best regards, Andrew.
