### ISSUE TITLE
From showing as email = "email@domain.co.uk", display = "" <list@X92BL001PPFP2AP.mail.domain.net>

### ISSUE THREAD

**Issue by chrisEthers** [datawookie/emayili#75]
Hello,

First of all thank you for this great package.

When using version {emayili}-0.4.16, emails are being received but the from argument is being put in to a list, and then shows like this to the recipient:

![image](https://user-images.githubusercontent.com/89844546/131496497-189d5dbc-3bfd-4c7f-b6e0-2443fd51774f.png)

...but when using {emayili}-0.4.10, the from address shows as the standard email address eg mail@domain.co.uk, which is how the recipients would like to see it.

I'm not sure if this is an issue in the package or something I am doing wrong or missing?

Any help or feedback would be greatly appreciated.

Kind regards

Chris

**Comment by pnacht** [comment]
I can confirm this is a regression. I have a script that sends an automated email daily and it worked just fine until I updated the package on my local machine (thankfully haven't updated the server which actually runs the automated script yet).

If I run the code on my local machine with the updated package:

``` r
library(emayili)
library(magrittr)

packageVersion("emayili")
#> [1] ‘0.4.16’

envelope() %>%
    from("me@me.com") %>%
    to("you@you.com") %>%
    subject("subject") %>%
    html("body") %>%
    print()
#> Date:         Tue, 31 Aug 2021 13:50:06 GMT
#> From:         list(email = "me@me.com", display = NA)  <--- pay attention to this line
#> To:           you@you.com
#> Subject:      subject
#> X-Mailer:     {emayili}-0.4.16
```

<sup>Created on 2021-08-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

And the email sent by the updated script comes out looking exactly like the "From:" output:

![image](https://user-images.githubusercontent.com/15221358/131517180-bc255fc9-2ff9-436a-9839-0d8275baa8b0.png)

However, if I run this on the remote with the old package:

``` r
library(emayili)
library(magrittr)

packageVersion("emayili")
#> [1] '0.4.10'

envelope() %>%
    from("me@me.com") %>%
    to("you@you.com") %>%
    subject("subject") %>%
    html("body") %>%
    print()
#> Date:         Tue, 31 Aug 2021 14:03:49 GMT
#> From:         me@me.com  <--- different!
#> To:           you@you.com
#> Subject:      subject
#> X-Mailer:     {emayili}-0.4.10
```

<sup>Created on 2021-08-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by datawookie** [comment]
Hi @chrisEthers and @pnacht, thanks for getting in touch about this issue. It has already been resolved in https://github.com/datawookie/emayili/issues/73. Unfortunately CRAN is currently not accepting package updates, so the only way to get the fixed package is to install from GitHub. I understand that CRAN submissions will be back online from tomorrow though, so I'll update immediately. Thanks, Andrew.

**Comment by chrisEthers** [comment]
Hi Andrew,

This is great, thank you very much for the swift reply.

Kind regards

Chris

**Comment by datawookie** [comment]
@chrisEthers and @pnacht this should be fixed in the version currently on CRAN (0.4.17).

**Comment by chrisEthers** [comment]
Hi @datawookie,

Hope you are well. Unfortunately I ran v 0.4.17 this morning but the issue did not seem to be fixed:

![image](https://user-images.githubusercontent.com/89844546/132195833-7fa02701-ad5f-4133-8d47-a9479deebfda.png)

Kind regards

Chris

**Comment by datawookie** [comment]
Hi @chrisEthers, I'm afraid that you have not really provided me with a lot to work on... However, I did find that there was an issue with empty `From` and `Sender` fields, which I have fixed. I've pushed the changes to GitHub. Could you please test for me?

```
remotes::install_github("datawookie/emayili", ref = "678582085753c015b20894ea676f3323665f63f3")
```

Thanks, Andrew.

**Comment by chrisEthers** [comment]
Hi @datawookie, apologies for the poor explanation.  I have used the repo above and it seems to be working perfectly now.

Many thanks for your help.

Kind regards

Chris

**Comment by datawookie** [comment]
Hi @chrisEthers, not at all. Any feedback is appreciated! And I'm getting better and joining the dots. :) Fantastic. Let me update CRAN. Again. For real this time. :) Best regards, Andrew.

**Comment by datawookie** [comment]
Hi @chrisEthers, version 0.4.18 is on CRAN. Please let me know if there are any further issues. Thanks, Andrew.
