### ISSUE TITLE
Undeliverable message due to bare line feed characters

### ISSUE THREAD

**Issue by jonspring** [datawookie/emayili#78]
Using my work's Office 365 email server, I can successfully send a text-only message, or a message with HTML in the body, but I get an error on the server side when I try to include markdown in the body using `render("Test")`. This is through my work's Office 365 email server.

```
> Your message to [work_email] couldn't be delivered.
> --
> Your message contains invalid characters (bare   line feed characters) which the email servers at
> [work_domain] don't support.
> 
> How to Fix It
> --
> It   appears that your email program added invalid characters (bare line feed   characters) into your
> message when you sent it. Try using a different email   program to send your message. If the problem
> continues send this non-delivery   report (NDR) message to your email admin for assistance.
```

Also, curiously, when I create the `email` object with `render()`, I get a warning, even though the Rmd has a title in the YAML:

```
> [WARNING] This document format requires a nonempty <title> element.
>   Defaulting to 'file31ac65764750.knit' as the title.
>   To specify a title, use 'title' in metadata or --metadata title="...".
```

```
library(emayili)
email <- envelope() %>%
  from(my_email) %>%
  to(my_email) %>%
  subject("Test email at {{Sys.time()}}") %>%
  # text("Testing 1-2-3")                              # works 
  # html("Here's some <strong>great</strong> html!")   # works
  # render("Test 1-2-3")                               # error: bare line feed chars   
  render("test_min.Rmd")                               # error: bare line feed chars
```

test_min.Rmd:

````
---
title: "Test"
output: html_document
---

```{r setup, include=FALSE}
plot(mtcars$mpg)
```
````

```
> sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] emayili_0.5.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7       bslib_0.2.5.1    jquerylib_0.1.4  pillar_1.6.1     compiler_4.1.0  
 [6] base64enc_0.1-3  tools_4.1.0      digest_0.6.27    jsonlite_1.7.2   evaluate_0.14   
[11] lifecycle_1.0.0  tibble_3.1.2     pkgconfig_2.0.3  rlang_0.4.11     DBI_1.1.1       
[16] commonmark_1.7   curl_4.3.2       xfun_0.23        fastmap_1.1.0    dplyr_1.0.7     
[21] stringr_1.4.0    httr_1.4.2       xml2_1.3.2       knitr_1.33       sass_0.4.0      
[26] generics_0.1.0   vctrs_0.3.8      triebeard_0.3.0  tidyselect_1.1.1 glue_1.4.2      
[31] R6_2.5.0         fansi_0.5.0      rmarkdown_2.11   purrr_0.3.4      tidyr_1.1.3     
[36] logger_0.2.1     magrittr_2.0.1   urltools_1.7.3   ellipsis_0.3.2   htmltools_0.5.2 
[41] assertthat_0.2.1 mime_0.11        keyring_1.2.0    utf8_1.2.1       stringi_1.6.2   
[46] crayon_1.4.1 
```

**Comment by datawookie** [comment]
Hi @jonspring,

Thank you for trying out `{emayili}` and taking the time to bring this issue to my attention.

Yes, Microsoft servers seem to be pedantic about using `"\r\n"` at the end of each line rather than the much more economical `"\n"`.

I've made a small tweak to the code and I'd appreciate you testing it for me before I merge it into `master`.

Could you please install as follows and then test? Thank you! Best regards, Andrew.

```
remotes::install_github("datawookie/emayili", ref = "8e81f552c5257ce7b114c5ea0f5ce0821e68993c")
```

**Comment by datawookie** [comment]
> Also, curiously, when I create the email object with render(), I get a warning, even though the Rmd has a title in the YAML

Are you sure?

I can't reproduce this behaviour with the following code:

```
envelope() %>%
  render("test_min.Rmd")
```

However I do get that warning when I do this:

```
envelope() %>%
  render("Test 1-2-3")
```

**Comment by jonspring** [comment]
Yes, I still get that error, here's the exact file: 
https://gist.github.com/jonspring/7de5506c66fa13dc07d9d4e8941d22b4

**Comment by jonspring** [comment]
I installed using the link and the email was received. However, the email body when I used `render("test_min.Rmd")` was just the text "test_min.Rmd" instead of the output of that markdown script.

**Comment by jonspring** [comment]
I updated using your update and it seems to have worked! (I had an error a few minutes ago due to my own mistake -- the Rmd was stored in a subdirectory of my project and I forgot to reference that subdirectory. That corrected the "missing title" issue you could not reproduce.)

The email went through with the formatted title Test in the body, and the plot attached as a png. I will read more of the documentation to see what I can do to make the png appear in the body of the email.

**Comment by datawookie** [comment]
Hi @jonspring,

Glad to know you got that working.

> I will read more of the documentation to see what I can do to make the png appear in the body of the email.

Can you give me some more information on what you are trying to do? You didn't mention a PNG file before. Is this a file generated by `render()` or is it a file that you're attaching separately?

Thanks, Andrew.

**Comment by jonspring** [comment]
My RMarkdown files are showing up differently in my work Outlook client on
the desktop vs. the Outlook app on my iphone. These might well be issues
upstream or downstream of emayili.

For the `test_min.Rmd` script using `html_document` that I included
originally, which has a base R `plot` in the only chunk, it appears on
desktop Outlook as an email that just shows the RMarkdown title *Test* in
the body, and nothing else, but the plot is attached as a png.  On the
Outlook app on my iphone, the plot appears in the body, as well as as an
attachment.

For a different test Rmd that used `flexdashboard::flex_dashboard`, the
output was cleaner, with charts visible in both desktop and mobile Outlook,
and no attachments. The only issue I had was a formatting one, where on
desktop Outlook a table of `gt::gt(head(mtcars))` had redundant lines above
and below each text.

**Comment by datawookie** [comment]
Hello @jonspring. Regards, Andrew.
