### ISSUE TITLE
Aligning RTL inline text to the right in emayili::render()

### ISSUE THREAD

**Issue by yoav-raskin** [datawookie/emayili#81]
Hi @datawookie,

I have a rmarkdown report with some inline text in an RTL language (Hebrew). When I render the report using `rmarkdown::render(here::here("Telem assessment reports", "telem_assessment_report_tashpab.Rmd"),
                  output_format = "html_document")` it works well. All the RTL inline text is aligned to the right in the HTML file. 

However, when I render and email the same report using `emayili::render()`, the RTL inline text still uses RTL direction (which is great!), but the paragraph is aligned to the left, like an English language paragraph, when it should be aligned to the right.
What can explain the difference between rendering HTML in `rmarkdown` and in `emayili`? Shouldn't it be the same?

This is how I format my RTL inline text in the .Rmd file:

```
<style>
  .rtl { direction:rtl;}
</style>
```

```
<div class="rtl">
# דו"ח תשפ"ב
הדו"ח מתייחס לפתיחת שנת תשפ"ב וכולל נתונים על שתי השלוחות
</div>
```

Also, is there a way to align `ggplot2` output to the right as well?

Thank you very much!
Yoav

**Comment by datawookie** [comment]
Hi @yoav-raskin, I never thought of this! :) But I'm sure we can fix it. Got quite a lot on my plate today, but I'll try to sort it out tomorrow morning. Thanks, Andrew.

**Comment by yoav-raskin** [comment]
Fantastic, that'll great!
Thanks so much

**Comment by datawookie** [comment]
Hi @yoav-raskin, okay, I've tinkered with this a bit and learned about the `direction` CSS directive in the process. I just wanted to check that we are aligned on what you are aiming for. Please take a look at the example below. Is that more or less what you are wanting? Best regards, Andrew.

![image](https://user-images.githubusercontent.com/6134409/134458225-bb886fbf-b01b-4811-90d1-3c772c19a0c2.png)

**Comment by yoav-raskin** [comment]
Yes, exactly.
The green text looks very good. It is both RTL and aligned to the right.
The plot is also aligned to the right as expected in a Hebrew document.

Thank you so much,
Yoav

**Comment by datawookie** [comment]
Wonderful. I'm going to just sort out these changes and push them to the repository.

Would you be okay if I used this as the basis for a short blog post?

**Comment by yoav-raskin** [comment]
Sure, no problem. I'll share the post around with Israeli R enthusiasts.

**Comment by datawookie** [comment]
Okay, I'm going to push these changes shorty. This is the setup for testing.

```r
library(emayili)

msg <- envelope() %>%
  from("alice@gmail.com") %>%
  to("bob@gmail.com")

smtp <- server(
    # Setup goes here.
)

msg %>%
  subject("Right-to-Left Text") %>%
  render("rtl.Rmd", css_files = "rtl.css") %>%
  smtp()
```

Here's `rtl.css`...

```css
.rtl {
  direction: rtl;
  color: green;
}

body {
  margin: 30px 0px;
}

figure {
  margin-bottom: 20px;
}

.rtl figcaption {
  direction: rtl;
}
```

... and this is `rtl.Rmd`.

````
---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer non magna magna. Etiam eu sapien nulla. Cras ac lectus non urna scelerisque porttitor ac non tortor. Aenean rutrum blandit lorem eu pellentesque. Duis suscipit mollis consequat. Mauris aliquam, augue ut aliquam varius, quam tellus rhoncus justo, ac ornare magna turpis quis felis. Nam vitae elit eget diam pellentesque fermentum sit amet viverra nunc. Nullam ac ipsum ac ligula finibus tempor. Aliquam sagittis sit amet odio id scelerisque. Nullam vitae accumsan justo, eu laoreet augue. Integer non pulvinar leo, vel tempor ante. Nullam id auctor magna.

<div class="rtl">
Maecenas ac mi sit amet purus lobortis condimentum. צחוק המעבורת, מהדובים של הכרית החופשית. מי רוצה לפספס, עצוב בחצר האחורית, כד רך. עכשיו הכאב של הכאב הוא לא הכאב של הטרדה, הצורך של אגמי החלבון של התפוז. אלמנט כלשהו, ​​וגם לא יסוד כימי של נדל"ן, מראית עין של מגוון כלי רכב לנחות, רגע לפני הספד החיים. אניאס הוא מחבר רכיב המחיר. אין פחד אלא אם להיות כנים. אני חי במייסר העצוב של הכדורגל שלי, בסמך הזן כמובן. אבל המענה והקשתות, או קצות האורקים. אל האגם או לפניו. הזמן של העמק לוקח. אפילו הפחד מהפחד, הקשתות או המעבורת, אתת האינטרנט. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. במקום הנכס, התרופות בקריקטורה. מספר שלם nus purus ut ligula aliquam vestibulum.

עד שהחתול הוא דו, הוא תמיד יהיה בבריאות אבל זמן טוב עכשיו. Fusce mollis nibh et nulla faucibus feugiat. זה אחד הרכבים שנבחרו. חי כדי להעלות את שנאת המערכת החיסונית. Curabitur vel risus commodo, malesuada justo vel, convallis sem. אבל הייתי בהריון עכשיו, אבל רועדת. אבל זה לא היה כיף.
</div>

```{r pressure, out.width="50%", fig.cap="A RTL figure caption", fig.class="rtl"}
plot(pressure)
```

<div class="rtl">
עצב המחלה, למעט הפחד מהיתרונות הכלכליים, במחיר העיקרי עצמו. Maecenas in fermentum nisi. עכשיו במסה אבל אלמנט המיטה של ​​החצאית. אבל לפעמים המכוער בחצר האחורית דוב, אבל זה היה ריגוש נחמד. המחיר צריך להיות מיושר עם הסיפון. בהתאם לכך, במסת המימון, יש להוציא את הפחד מהקריקטורה. בסיפון או לפני ולהשקיע. אבל הניתוח הצודק, השער מלפני וגם לא, ההשלכות של סוף האגם. חייו של כל אריה היו של מחמצת רכה ללא מסלול חיים. אבל משתיה עכשיו, אבל רק כמה. המסה חיה וקשוחה. עכשיו האריה הוא זן, כך שזה רק קצת שנאה לגיבור העל. אבל זה האלמנט האקולוגי הרך שלי. אפילו כד האריה הרך, ולא הרבה מהחכמים הציגו. אניאס רוצה אישה בהריון מעצבן, כך שכדור הארץ יהיה נחמד לאהוב אותו.

המחלה נושאת את הסבירות לסוף השבוע, והפחד מהכדורגל קשה. אבל האריה והאריה והילדים נמצאים במיטה. זה ברוטב צריך להגיד. אבל מבחינתו, צרות החיים מותירות הרבה חיים, הקריקטורה זקוקה לארוסים. עכשיו אני שונא את הגורמים, לא את הכאב ולא את הסביבה, הכניסה קלה. עכשיו הכניסה לחיי. מספר שלם gravida mattis laoreet. אף מחבר לא חכם לשנוא, הגיע הזמן להיות אהוב על השחקנים הקלים.
</div>

Cras fringilla nunc in tellus sagittis accumsan. Mauris nisi tellus, congue sit amet turpis nec, accumsan lacinia neque. Nulla facilisi. Aenean porta lectus nibh, ut vulputate mauris elementum vel. Morbi iaculis nibh quis consectetur porttitor. Duis vel placerat nunc. Nulla id eleifend tellus. 
````

**Comment by yoav-raskin** [comment]
Are all the commits already pushed to CRAN?

**Comment by datawookie** [comment]
Oh no, definitely not. Still have to test and go through the normal release cycle.

Just pushed to GitHub though. Can you please test after installing the following development version?

```
remotes::install_github("datawookie/emayili", ref = "dc0489d6ef95db85ae008eb75b110c6c9378c370")
```

**Comment by datawookie** [comment]
@yoav-raskin I had to push a patch to fix a minor issue (unrelated to RTL support).

```r
remotes::install_github("datawookie/emayili", ref = "18d8482d623344b0b9652e03aeee8f2bd5302e22")
```

Please let me know if this works for you so that I can merge the changes into the `master` branch.

**Comment by yoav-raskin** [comment]
Hi,

I was unable to replicate your output using the new push.

Is the knitr::opts_chunk$set(echo = TRUE) mandatory? I normally set it to
FALSE.

Why did you put inline text in an r chunk? Or was the inline text outside
the setup chunk? If so, how did you render plot(pressure) outside an r
chunk?
either way, it is not aligning.

Yoav

**Comment by datawookie** [comment]
Hi.

> I was unable to replicate your output using the new push.

It's hard for me to help you without more information. Simply saying that it doesn't work is not helpful for me to debug the problem. Can you please run your code and add my email address as one of the recipients? You can find it in the `DESCRIPTION` file.

> Is the knitr::opts_chunk$set(echo = TRUE) mandatory? I normally set it to FALSE.

Not at all. You can definitely set it to `FALSE`.

> Why did you put inline text in an r chunk?

I don't understand. What are you referring to?

Andrew.

**Comment by yoav-raskin** [comment]
Sure, sorry for being unclear. It should be in your inbox. 

I've used this envelope:
```
msg <- envelope() %>% 
  subject("Your report is here!") %>%
  emayili::render(here::here("Telem assessment reports", "telem_assessment_report_tashpab.Rmd"),
                  css_files = c(here::here("Telem assessment reports", "rtl.css"))
  )
```
The YAML in `telem_assessment_report_tashpab.Rmd` is:

```
output:
  html_document:
    css: "rtl.css"
```

**Comment by datawookie** [comment]
Okay, @yoav-raskin, the text looks fine to me: it's right-aligned.

![image](https://user-images.githubusercontent.com/6134409/134480586-1c9bd5f7-7a9d-4f51-8ee7-dd9848e71ee0.png)

The figures are centred though.

I took a look at the source of the email message and this is what I see.

![image](https://user-images.githubusercontent.com/6134409/134480755-e1e56ff3-1625-454c-a7f3-d8ab3a1c6e2d.png)

You don't seem to have the `rtl` class on the `<figure>` tags. I suspect that you didn't include the `fig.class` option on the code chunk. See my example above (repeated below).

````
```{r pressure, out.width="50%", fig.cap="A RTL figure caption", fig.class="rtl"}
plot(pressure)
```
````

**Comment by yoav-raskin** [comment]
Hi @datawookie,

You're right, I fixed that.
However, I still can't get the inline text\ggplots to align to the right (and take green font) when my recipient domain is Gmail. Perhaps this is a Gmail specific issue?

Thanks,
Yoav

**Comment by datawookie** [comment]
Oh, Gmail. Yes, they are very "special". I've been delaying dealing with this. Let me take another look.

**Comment by datawookie** [comment]
@yoav-raskin I've just sent you an email with a version that I _think_ works on Gmail. Please let me know. :crossed_fingers:

**Comment by yoav-raskin** [comment]
Hi @datawookie. Works perfectly. 

Is this something about `emayili::render() `, or the way the CSS file is specified? 

Yoav

**Comment by datawookie** [comment]
Great. I made another tweak to the way that the CSS is being inserted into the email. Blog post available tomorrow.
