### ISSUE TITLE
Probably a small mistake

### ISSUE THREAD

**Issue by ghost** [datawookie/emayili#83]
Hello and thank you for this package that looks very promising to me !

I wanted to use this package to create some weekly report and began with a simple example to understand how the package works. Could you help me understand where my problem is coming from ? I used the example from the Wiki.

My code is basically this : 

```
library(tidyverse)
library(emayili)

options(envelope_details = TRUE, envelope_invisible = FALSE)

smtp = server(
  host         = "XXX",
  port          = 25,
  username = "XXX"
)

envelope(
  from     = "XXX",  
  to         = "XXX",              
  subject = "A simple test")        %>% 
  render("pi.Rmd")                      %>% 
  smtp(verbose = TRUE)
```

The pi.Rmd file is simply : 
![image](https://user-images.githubusercontent.com/80798473/136072204-51047828-ffb3-4fed-96d3-11c3c22088f6.png)

Everything is working great to send and receive the message. Unfortunately, the HTML code won't display properly and the email I receive is this : 

![image](https://user-images.githubusercontent.com/80798473/136072230-ebb8e4d0-8406-4198-9341-6dcaa1e1f7e2.png)

Thank you for your help !

**Comment by datawookie** [comment]
Hi @Ignatu5, thanks for lodging this issue. I have just tested your code and it works fine for me. So I'm a little puzzled. Can you please forward the email to me at andrew@fathomdata.dev and I'll investigate further? Also can you please tell me what email client you are using to read your email (Gmail in a browser, Outlook, Thunderbird etc.)? Thanks, Andrew.

**Comment by ghost** [comment]
Hi @datawookie , thanks for the fast answer. It is weird that it works for you. I just forwarded you the email. I sent the email to 2 different adresses (professionnal and personnal) and I opened the email (professionnal) with outlook 2019, and with (personnal) outlook for android/outlook in browser. 

Thank you !

Sacha

**Comment by datawookie** [comment]
> It is weird that it works for you.

Well, not really. I am developing the package and I test regularly. So I'd expect it to work for me. It's other people who occasionally have trouble. But we will sort this out!

**Comment by ghost** [comment]
The problem has been solved with the help and kindness of @datawookie. I was using an old version of the package and the problem was caused by the presence of BareLine that my email server didn't accept to send or receive. After having updated the package, the problem disappeared. 

For people interested, here are 2 links to understand the problem better :

https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-6-11-in-exchange-online

https://docs.microsoft.com/en-us/exchange/troubleshoot/antispam-and-protection/smtpsend-barelinefeedsareillegal-when-tracing-messages
