### ISSUE TITLE
Comments & Keywords Header Fields

### ISSUE THREAD

**Issue by datawookie** [datawookie/emayili#85]
**Requirements:** Add the `Comments:` and `Keywords:` header fields.

More information on these fields can be found in [RFC 5322](https://www.rfc-editor.org/rfc/rfc5322.html).

You'll need to:

1. add a `comments()` function in `R/header-mail.R` and
2. add a `keywords()` function in `R/header-mail.R`.

Since the `Keywords:` field can accommodate a comma-separated list of items it would make sense for `keywords()` to handle a vector of arguments.

**Comment by Swechhya** [comment]
@datawookie If no one is working on this I can take this up.

**Comment by datawookie** [comment]
Yes, please, @Swechhya. That would be great.

**Comment by datawookie** [comment]
WIP at https://github.com/datawookie/emayili/pull/88.
