### ISSUE TITLE
Invalid URLs in README

### ISSUE THREAD

**Issue by datawookie** [datawookie/emayili#86]
**Requirements:** Fix the two URLs in `README.Rmd` which are getting flagged by CRAN checks.

```
Found the following (possibly) invalid URLs:
  URL: https://login.aol.com/account/security
    From: README.md
    Status: Error
    Message: error:1423506E:SSL routines:ssl_next_proto_validate:bad extension
  URL: https://login.yahoo.com/account/security
    From: README.md
    Status: Error
    Message: error:1423506E:SSL routines:ssl_next_proto_validate:bad extension
```

**Comment by DarkSoul26** [comment]
Shall I fix this?

**Comment by datawookie** [comment]
For sure, that'd be great! Thank you.

**Comment by Axiematic** [comment]
@datawookie just had a quick look at these, both URLs are actually valid. I think CRAN is flagging them because they require you to be signed in to access them. 

If I sign out of Yahoo/AOL  and follow either of the links above I am redirected to a sign-in / sign-up page. If I am signed in they work no problem.

**Comment by datawookie** [comment]
Hmmm. If they require login to access the information then maybe we should create a local summary of the content? This would mean that:

1. CRAN would no longer moan about links.
2. People wouldn't have to leave the page in order to peruse the relevant information.

It could be included in `README.md` or put into a separate file.

**Comment by ColinFay** [comment]
Possible explanation: they are redirects ?

```
colin:~ colin$ curl https://login.aol.com/account/security
Found. Redirecting to https://login.aol.com/myaccount/security/
```

```
colin:~ colin$ curl https://login.yahoo.com/account/security
Found. Redirecting to https://login.yahoo.com/myaccount/security/
```

**Comment by datawookie** [comment]
Yeah, @ColinFay! I think you are right. @Axiematic do you want to fix this for your Hacktoberfest contribution? Colin assuming that you are happy to let Emma nab this low hanging fruit?

**Comment by ColinFay** [comment]
Sure, no pblm!
