### ISSUE TITLE
Cannot send E-Mails with emayili > 0.5.6

### ISSUE THREAD

**Issue by stibu81** [datawookie/emayili#89]
Since version 0.6.0 I can no longer send emails with emayili with the same code that works fine with 0.5.3 to 0.5.6. Unfortunately, I did not manage to find the reason for this, but at least  I can let you know what I did and maybe you can spot the mistake.

This is basically the code that I've been using and that worked fine with 0.5.6. The `...` stand for values like hosts, email addresses and passwords, that I don't want to disclose here.

```r
library(emayili)

email <- envelope(
    to = ...,
    from = ...,
    subject = "Test",
    text = paste("emayili version ", packageVersion("emayili"))
  )

smtp <- server(
    host = ...,
    port = 465,
    username = ...,
    password = ...,
    max_times = 2
  )

smtp(email, verbose = TRUE)
```
I use this code to send a message to multiple recipients. (I also tried `resue = FALSE` which did not make any difference.) It works with emayili 0.5.6, but not with any newer version. I install the various versions like this

```
remotes::install_github("datawookie/emayili", ref = "v0.5.3")
```
If I install emayili like this and then restart the session, sending emails works for 0.5.3 to 0.5.6, but not for any of the newer version. The message that I get is always the following (where I again replaced personal information by `...`:

> Sending email to...:465/.
>   Trying ...:465...
> TCP_NODELAY set
> Connected to ... (...) port 465 (#0)
> Operation timed out after 10001 milliseconds with 0 out of 0 bytes received
> Closing connection 0

Of course, this is repeated for every attempt.

I'm using R 4.1.1 on Ubuntu 20.04.3 with up-to-date versions of all packages. I'm aware that this might not be enough information for you to figure out this and of course I'm happy to provide any additional information that you might need.

**Comment by datawookie** [comment]
Hi Stefan @stibu81,

Would you mind testing with the most recent version for me, please?

```R
remotes::install_github("datawookie/emayili", "v0.6.3")
```

Thanks, Andrew.

**Comment by stibu81** [comment]
Of course! I have now tested versions 0.6.0, 0.6.1, 0.6.2, and 0.6.3, all with the same result as described above.

However, I have now been able to send emails with version 0.5.4 to 0.5.6. Unfortunately, I can not say for sure what I did wrong before (maybe I forgot to restart the R session), but I have run multiple tests again and results seem consistent: 0.5.3 to 0.5.6 seem to work, the newer versions not. Sorry for the confusion! I updated the original post to reflect this, to make this a little less confusing.

**Comment by datawookie** [comment]
Weird, because the same code works for me:

```r
library(emayili)

email <- envelope(
  to = Sys.getenv("SMTP_USERNAME"),
  from = Sys.getenv("SMTP_USERNAME"),
  subject = "Test",
  text = paste("emayili version ", packageVersion("emayili"))
)

smtp <- server(
  host = Sys.getenv("SMTP_SERVER"),
  port = Sys.getenv("SMTP_PORT"),
  username = Sys.getenv("SMTP_USERNAME"),
  password = Sys.getenv("SMTP_PASSWORD"),
  max_times = 1
)

smtp(email, verbose = TRUE)
```

Looking back at the changes from v0.5.6 to v0.6.0 I suspect that this might have something to do with the way that the protocol is being handled.

Can you please indulge me by installing an updated version:

```r
remotes::install_github("datawookie/emayili", "d55e7ad829beee27ec763f52f712fcd3252b4c85")
```

Then try two options:

**Option 1**

```r
smtp <- server(
  host = Sys.getenv("SMTP_SERVER"),
  port = Sys.getenv("SMTP_PORT"),
  username = Sys.getenv("SMTP_USERNAME"),
  password = Sys.getenv("SMTP_PASSWORD"),
  protocol = "smtp",
  max_times = 1
)
```

**Option 2**

```r
smtp <- server(
  host = Sys.getenv("SMTP_SERVER"),
  port = Sys.getenv("SMTP_PORT"),
  username = Sys.getenv("SMTP_USERNAME"),
  password = Sys.getenv("SMTP_PASSWORD"),
  protocol = "smtps",
  max_times = 1
)
```

In case it's not evident, these two differ in the `protocol` argument.

**Comment by stibu81** [comment]
Using `protocol = "smtps"` did the trick, but only with the newest commit from GitHub (not even with the commit tagged v0.6.3). But for versions 0.6.0 to 0.6.3 (including the CRAN version), explicitly specifying `host = "smtps://..."` did the trick. And using `host = "smtp://..."` fails exactly with the message from my original post. Thank you very much for your help!

This is rather confusing for me and I would probably never have figured that out without your help. And I still don't understand what exactly went wrong and why it worked with the old versions. Do you think there is a way to change the documentation such that it is clear how to do this correctly? (I have, admittedly, very little understanding of how email actually works, but this is probably true for other users of your package as well.)

**Comment by datawookie** [comment]
> Using protocol = "smtps" did the trick, but only with the newest commit from GitHub (not even with the commit tagged v0.6.3).

Yeah, that commit was just for you. ;)

Okay, I have neatened things up and created another patched version.

You can install v0.6.4 from GitHub and this will (hopefully) work for you even without specifying the `protocol` argument as specified above (that was just an experiment to confirm my hypothesis). Please can you confirm that this works? Thanks!

I'll roll this out to CRAN in due course.

**Comment by stibu81** [comment]
A commit just for me? Wow! :-)

I can confirm that with 0.6.4, sending emails works with or without `protocol = "smtps"`. So this is perfect for me, thanks again!

However, using `host = "smtps://..."` does not work any more. This is no problem for me, but maybe this could break somebody else's code?

**Comment by datawookie** [comment]
Aha! Well, IMHO the protocol (SMTP or SMTPS) is not really part of the "host". But agreed, you have a good point. This is probably something that will not be uncommon. I've made an update where if the protocol is specified in the host then this receives highest priority.

Thanks for your patience and help with this. If you wouldn't mind doing a final test? You can use the same tag to install the updated version.

**Comment by stibu81** [comment]
Of course. I checked the following:

* `host = "x.y.ch"` without specifying `protocol`
* `host = "x.y.ch"` and `protocol = "smtps"`
* `host = "smtps://x.y.ch"` without specifying `protocol`
* `host = "smtps://x.y.ch"` and `protocol = "smtps"`

All four variants worked.

It's me who has to say thank you for taking the time to fix this (and for even creating this useful package in the first place)! From my point of view, this can be closed.

**Comment by datawookie** [comment]
Brilliant! Such a pleasure collaborating with you on this. If you ever have any further feedback, please let me know. Also feature requests. :)
