### ISSUE TITLE
Idea: add support for htmltools outputs

### ISSUE THREAD

**Issue by ColinFay** [datawookie/emayili#92]
First of all, thanks for this. really nifty! 

I would love to be able to natively support `{htmltools}` output for the `content` part of the email. 

```r
library(emayili)
library(htmltools)
email <- envelope() %>% html(
  tagList(
    h2("this"), 
    p("That")
  )
)
Error: Only a single message body allowed.
```

Same with a simple tag:

```r
email <- envelope() %>% html(
    h2("this")
)
```

```r
email <- envelope() %>% html(
  tagList(
    h2("this"), 
    p("That")
  ) %>% as.character()
)
```

Seem to work but casting in character might not be perfect :/ 

I wonder if `html` could do something like: 

```r 
taglist_to_char <- function(
  content
) {
  if (
    # Handling cases where we want to pass tags
    # from htmltools
    inherits(content, "shiny.tag.list") |
    inherits(content, "shiny.tag") 
    ){
    content <- as.character(content)
  }
  content
}

html <- function(
  msg,
  content,
  disposition = "inline",
  charset = "utf-8",
  encoding = "quoted-printable",
  css_files = c(),
  interpolate = TRUE,
  .open = "{{",
  .close = "}}",
  .envir = NULL
) {
  
  content <- taglist_to_char(content)

  check_message_body(content)

  [...]
}
```

```r
taglist_to_char(
  tagList(
    h2("this"),
    p("That")
  )
)
[1] "<h2>this</h2>\n<p>That</p>"
```

As usual, happy to PR :)

**Comment by datawookie** [comment]
Hi @ColinFay, yes! This is a great idea and I really like the fact that you'd be able to build the HTML in a structured, programmatic way rather than just dumping a great big string of HTML text.

I was wondering whether we could do away with the `tagList()` though and expose an interface that would allow you to simply do something like this:

```r
envelope() %>%
  html(
    h2("this"),
    p("That")
  )
```

WDYT?

**Comment by ColinFay** [comment]
I'm all for it, but that seems like a breaking change? 

I mean, `html("this", "that")` won't work anymore for anyone assuming `"that"` is for `content`?

Otherwise, that's pretty much doable via `...`. 

OTOH, I suppose that if one is using `h2("this"), p("That")`, they're coming from `{shiny}`, so they are pretty much familiar with `tagList()`.

Anyway, whatever option you like the best is good with me, let me know and I'll draft a PR :)

**Comment by philibe** [comment]
IMHO, I think me too than `tagList()` is a better solution than `html()` if we use shiny and emayili in the same software :)

But it's true, my last emayili software was not in shiny, but maybe later.

**Comment by datawookie** [comment]
Okay, how about a compromise?

Adapt `html()` so that it can handle a list as its first argument. If it's just a plain list then coerce to a `tagList`. Then apply something like @ColinFay's `taglist_to_char()`.

**Comment by datawookie** [comment]
I have quickly implemented this on the `htmltools` branch. Do you want to take a look and see if it does what you want? If you're happy with the functionality then the only outstanding thing is to update the test suite.

**Comment by ColinFay** [comment]
Ah, i was about to do a PR 🙊 

Will have a look

**Comment by datawookie** [comment]
Sorry, I just started playing with this and realised that it could be implemented quite quickly and easily. Very likely your implementation would have been neater than mine, so please feel free to amend. Also we need some tests... If you feel inclined to write those, that would be great too!

**Comment by ColinFay** [comment]
Great :)

i will do a PR then with code implementation + tests + doc !

btw I'll be building a shiny app for a client that sends email via smtp so I'll probably be back on this repo a couple of times in the near future ;)

**Comment by datawookie** [comment]
Feel free to leverage the content on the `htmltools` branch.

> btw I'll be building a shiny app for a client that sends email via smtp so I'll probably be back on this repo a couple of times in the near future ;)

Magic! Thrilled to hear that you'll be using this in a client project. Let me know if you run into any issues or if there are any features you'd like implemented.
