### ISSUE TITLE
Problem with MIME objects when updating from 0.5.6 to 0.6.1

### ISSUE THREAD

**Issue by fgoerlich** [datawookie/emayili#93]
Hi,
With version `0.5.6` I had no problem in sending this mail
```
email <- envelope() %>%
  from('goerlich@uv.es') %>%
  to(mail.alumno) %>%
  subject(paste('Prediccion con Datos de Corte Transversal: Nota de', NombreTest)) %>%
  text(texto) %>%
  attachment(paste0(alumnos$user[i],'_solucion.pdf')) %>%
  attachment(paste0(NombreTest,'.png'))
```

With version `0.6.1` I get a MIME object error.

If I drop the last line,
```
email <- envelope() %>%
  from('goerlich@uv.es') %>%
  to(mail.alumno) %>%
  subject(paste('Prediccion con Datos de Corte Transversal: Nota de', NombreTest)) %>%
  text(texto) %>%
  attachment(paste0(alumnos$user[i],'_solucion.pdf'))
```
everything works as expected, and I have no problems.

So the problems lies in the `.png` file.

Is this solved in a development version, or I have to go back to a previous version?
If this is the case, how may I install version `0.5.6` again?

Thanks a lot.

**Comment by datawookie** [comment]
Hi @fgoerlich,

It's always helpful if your example code is simple for me to reproduce the problem.

I distilled it down to the following:

```r
library(emayili)

email <- envelope() %>%
  text("Test text.") %>%
  attachment("test.pdf") %>%
  attachment("test.png")

as.character(email)
```

With this I get an error on v0.6.1. However, this error has been fixed and should no longer be a problem with the development version of `{emayili}`.

Please install from GitHub as follows:

```r
remotes::install_github("datawookie/emayili", ref = "v0.6.6")
```

I'll be pushing an update to CRAN in the next few days.

Best regards, Andrew.
